###################################################################

# Created by write_sdc on Sat Dec 7 15:40:43 2024

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current uA
set_max_transition 0.1 [current_design]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports clk]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports reset]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports enable]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[63]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[62]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[61]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[60]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[59]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[58]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[57]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[56]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[55]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[54]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[53]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[52]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[51]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[50]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[49]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[48]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[47]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[46]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[45]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[44]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[43]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[42]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[41]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[40]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[39]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[38]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[37]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[36]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[35]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[34]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[33]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[32]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[31]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[30]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[29]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[28]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[27]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[26]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[25]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[24]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[23]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[22]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[21]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[20]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[19]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[18]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[17]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[16]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[15]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[14]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[13]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[12]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[11]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[10]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[9]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[8]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[7]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[6]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[5]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[4]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[3]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[2]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[1]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_0[0]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[63]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[62]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[61]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[60]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[59]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[58]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[57]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[56]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[55]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[54]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[53]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[52]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[51]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[50]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[49]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[48]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[47]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[46]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[45]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[44]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[43]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[42]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[41]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[40]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[39]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[38]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[37]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[36]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[35]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[34]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[33]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[32]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[31]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[30]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[29]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[28]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[27]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[26]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[25]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[24]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[23]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[22]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[21]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[20]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[19]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[18]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[17]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[16]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[15]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[14]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[13]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[12]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[11]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[10]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[9]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[8]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[7]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[6]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[5]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[4]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[3]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[2]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[1]}]
set_driving_cell -lib_cell NBUFFX4_RVT -no_design_rule [get_ports {data_in_1[0]}]
set_load -pin_load 0.1 [get_ports {fft_out[511]}]
set_load -pin_load 0.1 [get_ports {fft_out[510]}]
set_load -pin_load 0.1 [get_ports {fft_out[509]}]
set_load -pin_load 0.1 [get_ports {fft_out[508]}]
set_load -pin_load 0.1 [get_ports {fft_out[507]}]
set_load -pin_load 0.1 [get_ports {fft_out[506]}]
set_load -pin_load 0.1 [get_ports {fft_out[505]}]
set_load -pin_load 0.1 [get_ports {fft_out[504]}]
set_load -pin_load 0.1 [get_ports {fft_out[503]}]
set_load -pin_load 0.1 [get_ports {fft_out[502]}]
set_load -pin_load 0.1 [get_ports {fft_out[501]}]
set_load -pin_load 0.1 [get_ports {fft_out[500]}]
set_load -pin_load 0.1 [get_ports {fft_out[499]}]
set_load -pin_load 0.1 [get_ports {fft_out[498]}]
set_load -pin_load 0.1 [get_ports {fft_out[497]}]
set_load -pin_load 0.1 [get_ports {fft_out[496]}]
set_load -pin_load 0.1 [get_ports {fft_out[495]}]
set_load -pin_load 0.1 [get_ports {fft_out[494]}]
set_load -pin_load 0.1 [get_ports {fft_out[493]}]
set_load -pin_load 0.1 [get_ports {fft_out[492]}]
set_load -pin_load 0.1 [get_ports {fft_out[491]}]
set_load -pin_load 0.1 [get_ports {fft_out[490]}]
set_load -pin_load 0.1 [get_ports {fft_out[489]}]
set_load -pin_load 0.1 [get_ports {fft_out[488]}]
set_load -pin_load 0.1 [get_ports {fft_out[487]}]
set_load -pin_load 0.1 [get_ports {fft_out[486]}]
set_load -pin_load 0.1 [get_ports {fft_out[485]}]
set_load -pin_load 0.1 [get_ports {fft_out[484]}]
set_load -pin_load 0.1 [get_ports {fft_out[483]}]
set_load -pin_load 0.1 [get_ports {fft_out[482]}]
set_load -pin_load 0.1 [get_ports {fft_out[481]}]
set_load -pin_load 0.1 [get_ports {fft_out[480]}]
set_load -pin_load 0.1 [get_ports {fft_out[479]}]
set_load -pin_load 0.1 [get_ports {fft_out[478]}]
set_load -pin_load 0.1 [get_ports {fft_out[477]}]
set_load -pin_load 0.1 [get_ports {fft_out[476]}]
set_load -pin_load 0.1 [get_ports {fft_out[475]}]
set_load -pin_load 0.1 [get_ports {fft_out[474]}]
set_load -pin_load 0.1 [get_ports {fft_out[473]}]
set_load -pin_load 0.1 [get_ports {fft_out[472]}]
set_load -pin_load 0.1 [get_ports {fft_out[471]}]
set_load -pin_load 0.1 [get_ports {fft_out[470]}]
set_load -pin_load 0.1 [get_ports {fft_out[469]}]
set_load -pin_load 0.1 [get_ports {fft_out[468]}]
set_load -pin_load 0.1 [get_ports {fft_out[467]}]
set_load -pin_load 0.1 [get_ports {fft_out[466]}]
set_load -pin_load 0.1 [get_ports {fft_out[465]}]
set_load -pin_load 0.1 [get_ports {fft_out[464]}]
set_load -pin_load 0.1 [get_ports {fft_out[463]}]
set_load -pin_load 0.1 [get_ports {fft_out[462]}]
set_load -pin_load 0.1 [get_ports {fft_out[461]}]
set_load -pin_load 0.1 [get_ports {fft_out[460]}]
set_load -pin_load 0.1 [get_ports {fft_out[459]}]
set_load -pin_load 0.1 [get_ports {fft_out[458]}]
set_load -pin_load 0.1 [get_ports {fft_out[457]}]
set_load -pin_load 0.1 [get_ports {fft_out[456]}]
set_load -pin_load 0.1 [get_ports {fft_out[455]}]
set_load -pin_load 0.1 [get_ports {fft_out[454]}]
set_load -pin_load 0.1 [get_ports {fft_out[453]}]
set_load -pin_load 0.1 [get_ports {fft_out[452]}]
set_load -pin_load 0.1 [get_ports {fft_out[451]}]
set_load -pin_load 0.1 [get_ports {fft_out[450]}]
set_load -pin_load 0.1 [get_ports {fft_out[449]}]
set_load -pin_load 0.1 [get_ports {fft_out[448]}]
set_load -pin_load 0.1 [get_ports {fft_out[447]}]
set_load -pin_load 0.1 [get_ports {fft_out[446]}]
set_load -pin_load 0.1 [get_ports {fft_out[445]}]
set_load -pin_load 0.1 [get_ports {fft_out[444]}]
set_load -pin_load 0.1 [get_ports {fft_out[443]}]
set_load -pin_load 0.1 [get_ports {fft_out[442]}]
set_load -pin_load 0.1 [get_ports {fft_out[441]}]
set_load -pin_load 0.1 [get_ports {fft_out[440]}]
set_load -pin_load 0.1 [get_ports {fft_out[439]}]
set_load -pin_load 0.1 [get_ports {fft_out[438]}]
set_load -pin_load 0.1 [get_ports {fft_out[437]}]
set_load -pin_load 0.1 [get_ports {fft_out[436]}]
set_load -pin_load 0.1 [get_ports {fft_out[435]}]
set_load -pin_load 0.1 [get_ports {fft_out[434]}]
set_load -pin_load 0.1 [get_ports {fft_out[433]}]
set_load -pin_load 0.1 [get_ports {fft_out[432]}]
set_load -pin_load 0.1 [get_ports {fft_out[431]}]
set_load -pin_load 0.1 [get_ports {fft_out[430]}]
set_load -pin_load 0.1 [get_ports {fft_out[429]}]
set_load -pin_load 0.1 [get_ports {fft_out[428]}]
set_load -pin_load 0.1 [get_ports {fft_out[427]}]
set_load -pin_load 0.1 [get_ports {fft_out[426]}]
set_load -pin_load 0.1 [get_ports {fft_out[425]}]
set_load -pin_load 0.1 [get_ports {fft_out[424]}]
set_load -pin_load 0.1 [get_ports {fft_out[423]}]
set_load -pin_load 0.1 [get_ports {fft_out[422]}]
set_load -pin_load 0.1 [get_ports {fft_out[421]}]
set_load -pin_load 0.1 [get_ports {fft_out[420]}]
set_load -pin_load 0.1 [get_ports {fft_out[419]}]
set_load -pin_load 0.1 [get_ports {fft_out[418]}]
set_load -pin_load 0.1 [get_ports {fft_out[417]}]
set_load -pin_load 0.1 [get_ports {fft_out[416]}]
set_load -pin_load 0.1 [get_ports {fft_out[415]}]
set_load -pin_load 0.1 [get_ports {fft_out[414]}]
set_load -pin_load 0.1 [get_ports {fft_out[413]}]
set_load -pin_load 0.1 [get_ports {fft_out[412]}]
set_load -pin_load 0.1 [get_ports {fft_out[411]}]
set_load -pin_load 0.1 [get_ports {fft_out[410]}]
set_load -pin_load 0.1 [get_ports {fft_out[409]}]
set_load -pin_load 0.1 [get_ports {fft_out[408]}]
set_load -pin_load 0.1 [get_ports {fft_out[407]}]
set_load -pin_load 0.1 [get_ports {fft_out[406]}]
set_load -pin_load 0.1 [get_ports {fft_out[405]}]
set_load -pin_load 0.1 [get_ports {fft_out[404]}]
set_load -pin_load 0.1 [get_ports {fft_out[403]}]
set_load -pin_load 0.1 [get_ports {fft_out[402]}]
set_load -pin_load 0.1 [get_ports {fft_out[401]}]
set_load -pin_load 0.1 [get_ports {fft_out[400]}]
set_load -pin_load 0.1 [get_ports {fft_out[399]}]
set_load -pin_load 0.1 [get_ports {fft_out[398]}]
set_load -pin_load 0.1 [get_ports {fft_out[397]}]
set_load -pin_load 0.1 [get_ports {fft_out[396]}]
set_load -pin_load 0.1 [get_ports {fft_out[395]}]
set_load -pin_load 0.1 [get_ports {fft_out[394]}]
set_load -pin_load 0.1 [get_ports {fft_out[393]}]
set_load -pin_load 0.1 [get_ports {fft_out[392]}]
set_load -pin_load 0.1 [get_ports {fft_out[391]}]
set_load -pin_load 0.1 [get_ports {fft_out[390]}]
set_load -pin_load 0.1 [get_ports {fft_out[389]}]
set_load -pin_load 0.1 [get_ports {fft_out[388]}]
set_load -pin_load 0.1 [get_ports {fft_out[387]}]
set_load -pin_load 0.1 [get_ports {fft_out[386]}]
set_load -pin_load 0.1 [get_ports {fft_out[385]}]
set_load -pin_load 0.1 [get_ports {fft_out[384]}]
set_load -pin_load 0.1 [get_ports {fft_out[383]}]
set_load -pin_load 0.1 [get_ports {fft_out[382]}]
set_load -pin_load 0.1 [get_ports {fft_out[381]}]
set_load -pin_load 0.1 [get_ports {fft_out[380]}]
set_load -pin_load 0.1 [get_ports {fft_out[379]}]
set_load -pin_load 0.1 [get_ports {fft_out[378]}]
set_load -pin_load 0.1 [get_ports {fft_out[377]}]
set_load -pin_load 0.1 [get_ports {fft_out[376]}]
set_load -pin_load 0.1 [get_ports {fft_out[375]}]
set_load -pin_load 0.1 [get_ports {fft_out[374]}]
set_load -pin_load 0.1 [get_ports {fft_out[373]}]
set_load -pin_load 0.1 [get_ports {fft_out[372]}]
set_load -pin_load 0.1 [get_ports {fft_out[371]}]
set_load -pin_load 0.1 [get_ports {fft_out[370]}]
set_load -pin_load 0.1 [get_ports {fft_out[369]}]
set_load -pin_load 0.1 [get_ports {fft_out[368]}]
set_load -pin_load 0.1 [get_ports {fft_out[367]}]
set_load -pin_load 0.1 [get_ports {fft_out[366]}]
set_load -pin_load 0.1 [get_ports {fft_out[365]}]
set_load -pin_load 0.1 [get_ports {fft_out[364]}]
set_load -pin_load 0.1 [get_ports {fft_out[363]}]
set_load -pin_load 0.1 [get_ports {fft_out[362]}]
set_load -pin_load 0.1 [get_ports {fft_out[361]}]
set_load -pin_load 0.1 [get_ports {fft_out[360]}]
set_load -pin_load 0.1 [get_ports {fft_out[359]}]
set_load -pin_load 0.1 [get_ports {fft_out[358]}]
set_load -pin_load 0.1 [get_ports {fft_out[357]}]
set_load -pin_load 0.1 [get_ports {fft_out[356]}]
set_load -pin_load 0.1 [get_ports {fft_out[355]}]
set_load -pin_load 0.1 [get_ports {fft_out[354]}]
set_load -pin_load 0.1 [get_ports {fft_out[353]}]
set_load -pin_load 0.1 [get_ports {fft_out[352]}]
set_load -pin_load 0.1 [get_ports {fft_out[351]}]
set_load -pin_load 0.1 [get_ports {fft_out[350]}]
set_load -pin_load 0.1 [get_ports {fft_out[349]}]
set_load -pin_load 0.1 [get_ports {fft_out[348]}]
set_load -pin_load 0.1 [get_ports {fft_out[347]}]
set_load -pin_load 0.1 [get_ports {fft_out[346]}]
set_load -pin_load 0.1 [get_ports {fft_out[345]}]
set_load -pin_load 0.1 [get_ports {fft_out[344]}]
set_load -pin_load 0.1 [get_ports {fft_out[343]}]
set_load -pin_load 0.1 [get_ports {fft_out[342]}]
set_load -pin_load 0.1 [get_ports {fft_out[341]}]
set_load -pin_load 0.1 [get_ports {fft_out[340]}]
set_load -pin_load 0.1 [get_ports {fft_out[339]}]
set_load -pin_load 0.1 [get_ports {fft_out[338]}]
set_load -pin_load 0.1 [get_ports {fft_out[337]}]
set_load -pin_load 0.1 [get_ports {fft_out[336]}]
set_load -pin_load 0.1 [get_ports {fft_out[335]}]
set_load -pin_load 0.1 [get_ports {fft_out[334]}]
set_load -pin_load 0.1 [get_ports {fft_out[333]}]
set_load -pin_load 0.1 [get_ports {fft_out[332]}]
set_load -pin_load 0.1 [get_ports {fft_out[331]}]
set_load -pin_load 0.1 [get_ports {fft_out[330]}]
set_load -pin_load 0.1 [get_ports {fft_out[329]}]
set_load -pin_load 0.1 [get_ports {fft_out[328]}]
set_load -pin_load 0.1 [get_ports {fft_out[327]}]
set_load -pin_load 0.1 [get_ports {fft_out[326]}]
set_load -pin_load 0.1 [get_ports {fft_out[325]}]
set_load -pin_load 0.1 [get_ports {fft_out[324]}]
set_load -pin_load 0.1 [get_ports {fft_out[323]}]
set_load -pin_load 0.1 [get_ports {fft_out[322]}]
set_load -pin_load 0.1 [get_ports {fft_out[321]}]
set_load -pin_load 0.1 [get_ports {fft_out[320]}]
set_load -pin_load 0.1 [get_ports {fft_out[319]}]
set_load -pin_load 0.1 [get_ports {fft_out[318]}]
set_load -pin_load 0.1 [get_ports {fft_out[317]}]
set_load -pin_load 0.1 [get_ports {fft_out[316]}]
set_load -pin_load 0.1 [get_ports {fft_out[315]}]
set_load -pin_load 0.1 [get_ports {fft_out[314]}]
set_load -pin_load 0.1 [get_ports {fft_out[313]}]
set_load -pin_load 0.1 [get_ports {fft_out[312]}]
set_load -pin_load 0.1 [get_ports {fft_out[311]}]
set_load -pin_load 0.1 [get_ports {fft_out[310]}]
set_load -pin_load 0.1 [get_ports {fft_out[309]}]
set_load -pin_load 0.1 [get_ports {fft_out[308]}]
set_load -pin_load 0.1 [get_ports {fft_out[307]}]
set_load -pin_load 0.1 [get_ports {fft_out[306]}]
set_load -pin_load 0.1 [get_ports {fft_out[305]}]
set_load -pin_load 0.1 [get_ports {fft_out[304]}]
set_load -pin_load 0.1 [get_ports {fft_out[303]}]
set_load -pin_load 0.1 [get_ports {fft_out[302]}]
set_load -pin_load 0.1 [get_ports {fft_out[301]}]
set_load -pin_load 0.1 [get_ports {fft_out[300]}]
set_load -pin_load 0.1 [get_ports {fft_out[299]}]
set_load -pin_load 0.1 [get_ports {fft_out[298]}]
set_load -pin_load 0.1 [get_ports {fft_out[297]}]
set_load -pin_load 0.1 [get_ports {fft_out[296]}]
set_load -pin_load 0.1 [get_ports {fft_out[295]}]
set_load -pin_load 0.1 [get_ports {fft_out[294]}]
set_load -pin_load 0.1 [get_ports {fft_out[293]}]
set_load -pin_load 0.1 [get_ports {fft_out[292]}]
set_load -pin_load 0.1 [get_ports {fft_out[291]}]
set_load -pin_load 0.1 [get_ports {fft_out[290]}]
set_load -pin_load 0.1 [get_ports {fft_out[289]}]
set_load -pin_load 0.1 [get_ports {fft_out[288]}]
set_load -pin_load 0.1 [get_ports {fft_out[287]}]
set_load -pin_load 0.1 [get_ports {fft_out[286]}]
set_load -pin_load 0.1 [get_ports {fft_out[285]}]
set_load -pin_load 0.1 [get_ports {fft_out[284]}]
set_load -pin_load 0.1 [get_ports {fft_out[283]}]
set_load -pin_load 0.1 [get_ports {fft_out[282]}]
set_load -pin_load 0.1 [get_ports {fft_out[281]}]
set_load -pin_load 0.1 [get_ports {fft_out[280]}]
set_load -pin_load 0.1 [get_ports {fft_out[279]}]
set_load -pin_load 0.1 [get_ports {fft_out[278]}]
set_load -pin_load 0.1 [get_ports {fft_out[277]}]
set_load -pin_load 0.1 [get_ports {fft_out[276]}]
set_load -pin_load 0.1 [get_ports {fft_out[275]}]
set_load -pin_load 0.1 [get_ports {fft_out[274]}]
set_load -pin_load 0.1 [get_ports {fft_out[273]}]
set_load -pin_load 0.1 [get_ports {fft_out[272]}]
set_load -pin_load 0.1 [get_ports {fft_out[271]}]
set_load -pin_load 0.1 [get_ports {fft_out[270]}]
set_load -pin_load 0.1 [get_ports {fft_out[269]}]
set_load -pin_load 0.1 [get_ports {fft_out[268]}]
set_load -pin_load 0.1 [get_ports {fft_out[267]}]
set_load -pin_load 0.1 [get_ports {fft_out[266]}]
set_load -pin_load 0.1 [get_ports {fft_out[265]}]
set_load -pin_load 0.1 [get_ports {fft_out[264]}]
set_load -pin_load 0.1 [get_ports {fft_out[263]}]
set_load -pin_load 0.1 [get_ports {fft_out[262]}]
set_load -pin_load 0.1 [get_ports {fft_out[261]}]
set_load -pin_load 0.1 [get_ports {fft_out[260]}]
set_load -pin_load 0.1 [get_ports {fft_out[259]}]
set_load -pin_load 0.1 [get_ports {fft_out[258]}]
set_load -pin_load 0.1 [get_ports {fft_out[257]}]
set_load -pin_load 0.1 [get_ports {fft_out[256]}]
set_load -pin_load 0.1 [get_ports {fft_out[255]}]
set_load -pin_load 0.1 [get_ports {fft_out[254]}]
set_load -pin_load 0.1 [get_ports {fft_out[253]}]
set_load -pin_load 0.1 [get_ports {fft_out[252]}]
set_load -pin_load 0.1 [get_ports {fft_out[251]}]
set_load -pin_load 0.1 [get_ports {fft_out[250]}]
set_load -pin_load 0.1 [get_ports {fft_out[249]}]
set_load -pin_load 0.1 [get_ports {fft_out[248]}]
set_load -pin_load 0.1 [get_ports {fft_out[247]}]
set_load -pin_load 0.1 [get_ports {fft_out[246]}]
set_load -pin_load 0.1 [get_ports {fft_out[245]}]
set_load -pin_load 0.1 [get_ports {fft_out[244]}]
set_load -pin_load 0.1 [get_ports {fft_out[243]}]
set_load -pin_load 0.1 [get_ports {fft_out[242]}]
set_load -pin_load 0.1 [get_ports {fft_out[241]}]
set_load -pin_load 0.1 [get_ports {fft_out[240]}]
set_load -pin_load 0.1 [get_ports {fft_out[239]}]
set_load -pin_load 0.1 [get_ports {fft_out[238]}]
set_load -pin_load 0.1 [get_ports {fft_out[237]}]
set_load -pin_load 0.1 [get_ports {fft_out[236]}]
set_load -pin_load 0.1 [get_ports {fft_out[235]}]
set_load -pin_load 0.1 [get_ports {fft_out[234]}]
set_load -pin_load 0.1 [get_ports {fft_out[233]}]
set_load -pin_load 0.1 [get_ports {fft_out[232]}]
set_load -pin_load 0.1 [get_ports {fft_out[231]}]
set_load -pin_load 0.1 [get_ports {fft_out[230]}]
set_load -pin_load 0.1 [get_ports {fft_out[229]}]
set_load -pin_load 0.1 [get_ports {fft_out[228]}]
set_load -pin_load 0.1 [get_ports {fft_out[227]}]
set_load -pin_load 0.1 [get_ports {fft_out[226]}]
set_load -pin_load 0.1 [get_ports {fft_out[225]}]
set_load -pin_load 0.1 [get_ports {fft_out[224]}]
set_load -pin_load 0.1 [get_ports {fft_out[223]}]
set_load -pin_load 0.1 [get_ports {fft_out[222]}]
set_load -pin_load 0.1 [get_ports {fft_out[221]}]
set_load -pin_load 0.1 [get_ports {fft_out[220]}]
set_load -pin_load 0.1 [get_ports {fft_out[219]}]
set_load -pin_load 0.1 [get_ports {fft_out[218]}]
set_load -pin_load 0.1 [get_ports {fft_out[217]}]
set_load -pin_load 0.1 [get_ports {fft_out[216]}]
set_load -pin_load 0.1 [get_ports {fft_out[215]}]
set_load -pin_load 0.1 [get_ports {fft_out[214]}]
set_load -pin_load 0.1 [get_ports {fft_out[213]}]
set_load -pin_load 0.1 [get_ports {fft_out[212]}]
set_load -pin_load 0.1 [get_ports {fft_out[211]}]
set_load -pin_load 0.1 [get_ports {fft_out[210]}]
set_load -pin_load 0.1 [get_ports {fft_out[209]}]
set_load -pin_load 0.1 [get_ports {fft_out[208]}]
set_load -pin_load 0.1 [get_ports {fft_out[207]}]
set_load -pin_load 0.1 [get_ports {fft_out[206]}]
set_load -pin_load 0.1 [get_ports {fft_out[205]}]
set_load -pin_load 0.1 [get_ports {fft_out[204]}]
set_load -pin_load 0.1 [get_ports {fft_out[203]}]
set_load -pin_load 0.1 [get_ports {fft_out[202]}]
set_load -pin_load 0.1 [get_ports {fft_out[201]}]
set_load -pin_load 0.1 [get_ports {fft_out[200]}]
set_load -pin_load 0.1 [get_ports {fft_out[199]}]
set_load -pin_load 0.1 [get_ports {fft_out[198]}]
set_load -pin_load 0.1 [get_ports {fft_out[197]}]
set_load -pin_load 0.1 [get_ports {fft_out[196]}]
set_load -pin_load 0.1 [get_ports {fft_out[195]}]
set_load -pin_load 0.1 [get_ports {fft_out[194]}]
set_load -pin_load 0.1 [get_ports {fft_out[193]}]
set_load -pin_load 0.1 [get_ports {fft_out[192]}]
set_load -pin_load 0.1 [get_ports {fft_out[191]}]
set_load -pin_load 0.1 [get_ports {fft_out[190]}]
set_load -pin_load 0.1 [get_ports {fft_out[189]}]
set_load -pin_load 0.1 [get_ports {fft_out[188]}]
set_load -pin_load 0.1 [get_ports {fft_out[187]}]
set_load -pin_load 0.1 [get_ports {fft_out[186]}]
set_load -pin_load 0.1 [get_ports {fft_out[185]}]
set_load -pin_load 0.1 [get_ports {fft_out[184]}]
set_load -pin_load 0.1 [get_ports {fft_out[183]}]
set_load -pin_load 0.1 [get_ports {fft_out[182]}]
set_load -pin_load 0.1 [get_ports {fft_out[181]}]
set_load -pin_load 0.1 [get_ports {fft_out[180]}]
set_load -pin_load 0.1 [get_ports {fft_out[179]}]
set_load -pin_load 0.1 [get_ports {fft_out[178]}]
set_load -pin_load 0.1 [get_ports {fft_out[177]}]
set_load -pin_load 0.1 [get_ports {fft_out[176]}]
set_load -pin_load 0.1 [get_ports {fft_out[175]}]
set_load -pin_load 0.1 [get_ports {fft_out[174]}]
set_load -pin_load 0.1 [get_ports {fft_out[173]}]
set_load -pin_load 0.1 [get_ports {fft_out[172]}]
set_load -pin_load 0.1 [get_ports {fft_out[171]}]
set_load -pin_load 0.1 [get_ports {fft_out[170]}]
set_load -pin_load 0.1 [get_ports {fft_out[169]}]
set_load -pin_load 0.1 [get_ports {fft_out[168]}]
set_load -pin_load 0.1 [get_ports {fft_out[167]}]
set_load -pin_load 0.1 [get_ports {fft_out[166]}]
set_load -pin_load 0.1 [get_ports {fft_out[165]}]
set_load -pin_load 0.1 [get_ports {fft_out[164]}]
set_load -pin_load 0.1 [get_ports {fft_out[163]}]
set_load -pin_load 0.1 [get_ports {fft_out[162]}]
set_load -pin_load 0.1 [get_ports {fft_out[161]}]
set_load -pin_load 0.1 [get_ports {fft_out[160]}]
set_load -pin_load 0.1 [get_ports {fft_out[159]}]
set_load -pin_load 0.1 [get_ports {fft_out[158]}]
set_load -pin_load 0.1 [get_ports {fft_out[157]}]
set_load -pin_load 0.1 [get_ports {fft_out[156]}]
set_load -pin_load 0.1 [get_ports {fft_out[155]}]
set_load -pin_load 0.1 [get_ports {fft_out[154]}]
set_load -pin_load 0.1 [get_ports {fft_out[153]}]
set_load -pin_load 0.1 [get_ports {fft_out[152]}]
set_load -pin_load 0.1 [get_ports {fft_out[151]}]
set_load -pin_load 0.1 [get_ports {fft_out[150]}]
set_load -pin_load 0.1 [get_ports {fft_out[149]}]
set_load -pin_load 0.1 [get_ports {fft_out[148]}]
set_load -pin_load 0.1 [get_ports {fft_out[147]}]
set_load -pin_load 0.1 [get_ports {fft_out[146]}]
set_load -pin_load 0.1 [get_ports {fft_out[145]}]
set_load -pin_load 0.1 [get_ports {fft_out[144]}]
set_load -pin_load 0.1 [get_ports {fft_out[143]}]
set_load -pin_load 0.1 [get_ports {fft_out[142]}]
set_load -pin_load 0.1 [get_ports {fft_out[141]}]
set_load -pin_load 0.1 [get_ports {fft_out[140]}]
set_load -pin_load 0.1 [get_ports {fft_out[139]}]
set_load -pin_load 0.1 [get_ports {fft_out[138]}]
set_load -pin_load 0.1 [get_ports {fft_out[137]}]
set_load -pin_load 0.1 [get_ports {fft_out[136]}]
set_load -pin_load 0.1 [get_ports {fft_out[135]}]
set_load -pin_load 0.1 [get_ports {fft_out[134]}]
set_load -pin_load 0.1 [get_ports {fft_out[133]}]
set_load -pin_load 0.1 [get_ports {fft_out[132]}]
set_load -pin_load 0.1 [get_ports {fft_out[131]}]
set_load -pin_load 0.1 [get_ports {fft_out[130]}]
set_load -pin_load 0.1 [get_ports {fft_out[129]}]
set_load -pin_load 0.1 [get_ports {fft_out[128]}]
set_load -pin_load 0.1 [get_ports {fft_out[127]}]
set_load -pin_load 0.1 [get_ports {fft_out[126]}]
set_load -pin_load 0.1 [get_ports {fft_out[125]}]
set_load -pin_load 0.1 [get_ports {fft_out[124]}]
set_load -pin_load 0.1 [get_ports {fft_out[123]}]
set_load -pin_load 0.1 [get_ports {fft_out[122]}]
set_load -pin_load 0.1 [get_ports {fft_out[121]}]
set_load -pin_load 0.1 [get_ports {fft_out[120]}]
set_load -pin_load 0.1 [get_ports {fft_out[119]}]
set_load -pin_load 0.1 [get_ports {fft_out[118]}]
set_load -pin_load 0.1 [get_ports {fft_out[117]}]
set_load -pin_load 0.1 [get_ports {fft_out[116]}]
set_load -pin_load 0.1 [get_ports {fft_out[115]}]
set_load -pin_load 0.1 [get_ports {fft_out[114]}]
set_load -pin_load 0.1 [get_ports {fft_out[113]}]
set_load -pin_load 0.1 [get_ports {fft_out[112]}]
set_load -pin_load 0.1 [get_ports {fft_out[111]}]
set_load -pin_load 0.1 [get_ports {fft_out[110]}]
set_load -pin_load 0.1 [get_ports {fft_out[109]}]
set_load -pin_load 0.1 [get_ports {fft_out[108]}]
set_load -pin_load 0.1 [get_ports {fft_out[107]}]
set_load -pin_load 0.1 [get_ports {fft_out[106]}]
set_load -pin_load 0.1 [get_ports {fft_out[105]}]
set_load -pin_load 0.1 [get_ports {fft_out[104]}]
set_load -pin_load 0.1 [get_ports {fft_out[103]}]
set_load -pin_load 0.1 [get_ports {fft_out[102]}]
set_load -pin_load 0.1 [get_ports {fft_out[101]}]
set_load -pin_load 0.1 [get_ports {fft_out[100]}]
set_load -pin_load 0.1 [get_ports {fft_out[99]}]
set_load -pin_load 0.1 [get_ports {fft_out[98]}]
set_load -pin_load 0.1 [get_ports {fft_out[97]}]
set_load -pin_load 0.1 [get_ports {fft_out[96]}]
set_load -pin_load 0.1 [get_ports {fft_out[95]}]
set_load -pin_load 0.1 [get_ports {fft_out[94]}]
set_load -pin_load 0.1 [get_ports {fft_out[93]}]
set_load -pin_load 0.1 [get_ports {fft_out[92]}]
set_load -pin_load 0.1 [get_ports {fft_out[91]}]
set_load -pin_load 0.1 [get_ports {fft_out[90]}]
set_load -pin_load 0.1 [get_ports {fft_out[89]}]
set_load -pin_load 0.1 [get_ports {fft_out[88]}]
set_load -pin_load 0.1 [get_ports {fft_out[87]}]
set_load -pin_load 0.1 [get_ports {fft_out[86]}]
set_load -pin_load 0.1 [get_ports {fft_out[85]}]
set_load -pin_load 0.1 [get_ports {fft_out[84]}]
set_load -pin_load 0.1 [get_ports {fft_out[83]}]
set_load -pin_load 0.1 [get_ports {fft_out[82]}]
set_load -pin_load 0.1 [get_ports {fft_out[81]}]
set_load -pin_load 0.1 [get_ports {fft_out[80]}]
set_load -pin_load 0.1 [get_ports {fft_out[79]}]
set_load -pin_load 0.1 [get_ports {fft_out[78]}]
set_load -pin_load 0.1 [get_ports {fft_out[77]}]
set_load -pin_load 0.1 [get_ports {fft_out[76]}]
set_load -pin_load 0.1 [get_ports {fft_out[75]}]
set_load -pin_load 0.1 [get_ports {fft_out[74]}]
set_load -pin_load 0.1 [get_ports {fft_out[73]}]
set_load -pin_load 0.1 [get_ports {fft_out[72]}]
set_load -pin_load 0.1 [get_ports {fft_out[71]}]
set_load -pin_load 0.1 [get_ports {fft_out[70]}]
set_load -pin_load 0.1 [get_ports {fft_out[69]}]
set_load -pin_load 0.1 [get_ports {fft_out[68]}]
set_load -pin_load 0.1 [get_ports {fft_out[67]}]
set_load -pin_load 0.1 [get_ports {fft_out[66]}]
set_load -pin_load 0.1 [get_ports {fft_out[65]}]
set_load -pin_load 0.1 [get_ports {fft_out[64]}]
set_load -pin_load 0.1 [get_ports {fft_out[63]}]
set_load -pin_load 0.1 [get_ports {fft_out[62]}]
set_load -pin_load 0.1 [get_ports {fft_out[61]}]
set_load -pin_load 0.1 [get_ports {fft_out[60]}]
set_load -pin_load 0.1 [get_ports {fft_out[59]}]
set_load -pin_load 0.1 [get_ports {fft_out[58]}]
set_load -pin_load 0.1 [get_ports {fft_out[57]}]
set_load -pin_load 0.1 [get_ports {fft_out[56]}]
set_load -pin_load 0.1 [get_ports {fft_out[55]}]
set_load -pin_load 0.1 [get_ports {fft_out[54]}]
set_load -pin_load 0.1 [get_ports {fft_out[53]}]
set_load -pin_load 0.1 [get_ports {fft_out[52]}]
set_load -pin_load 0.1 [get_ports {fft_out[51]}]
set_load -pin_load 0.1 [get_ports {fft_out[50]}]
set_load -pin_load 0.1 [get_ports {fft_out[49]}]
set_load -pin_load 0.1 [get_ports {fft_out[48]}]
set_load -pin_load 0.1 [get_ports {fft_out[47]}]
set_load -pin_load 0.1 [get_ports {fft_out[46]}]
set_load -pin_load 0.1 [get_ports {fft_out[45]}]
set_load -pin_load 0.1 [get_ports {fft_out[44]}]
set_load -pin_load 0.1 [get_ports {fft_out[43]}]
set_load -pin_load 0.1 [get_ports {fft_out[42]}]
set_load -pin_load 0.1 [get_ports {fft_out[41]}]
set_load -pin_load 0.1 [get_ports {fft_out[40]}]
set_load -pin_load 0.1 [get_ports {fft_out[39]}]
set_load -pin_load 0.1 [get_ports {fft_out[38]}]
set_load -pin_load 0.1 [get_ports {fft_out[37]}]
set_load -pin_load 0.1 [get_ports {fft_out[36]}]
set_load -pin_load 0.1 [get_ports {fft_out[35]}]
set_load -pin_load 0.1 [get_ports {fft_out[34]}]
set_load -pin_load 0.1 [get_ports {fft_out[33]}]
set_load -pin_load 0.1 [get_ports {fft_out[32]}]
set_load -pin_load 0.1 [get_ports {fft_out[31]}]
set_load -pin_load 0.1 [get_ports {fft_out[30]}]
set_load -pin_load 0.1 [get_ports {fft_out[29]}]
set_load -pin_load 0.1 [get_ports {fft_out[28]}]
set_load -pin_load 0.1 [get_ports {fft_out[27]}]
set_load -pin_load 0.1 [get_ports {fft_out[26]}]
set_load -pin_load 0.1 [get_ports {fft_out[25]}]
set_load -pin_load 0.1 [get_ports {fft_out[24]}]
set_load -pin_load 0.1 [get_ports {fft_out[23]}]
set_load -pin_load 0.1 [get_ports {fft_out[22]}]
set_load -pin_load 0.1 [get_ports {fft_out[21]}]
set_load -pin_load 0.1 [get_ports {fft_out[20]}]
set_load -pin_load 0.1 [get_ports {fft_out[19]}]
set_load -pin_load 0.1 [get_ports {fft_out[18]}]
set_load -pin_load 0.1 [get_ports {fft_out[17]}]
set_load -pin_load 0.1 [get_ports {fft_out[16]}]
set_load -pin_load 0.1 [get_ports {fft_out[15]}]
set_load -pin_load 0.1 [get_ports {fft_out[14]}]
set_load -pin_load 0.1 [get_ports {fft_out[13]}]
set_load -pin_load 0.1 [get_ports {fft_out[12]}]
set_load -pin_load 0.1 [get_ports {fft_out[11]}]
set_load -pin_load 0.1 [get_ports {fft_out[10]}]
set_load -pin_load 0.1 [get_ports {fft_out[9]}]
set_load -pin_load 0.1 [get_ports {fft_out[8]}]
set_load -pin_load 0.1 [get_ports {fft_out[7]}]
set_load -pin_load 0.1 [get_ports {fft_out[6]}]
set_load -pin_load 0.1 [get_ports {fft_out[5]}]
set_load -pin_load 0.1 [get_ports {fft_out[4]}]
set_load -pin_load 0.1 [get_ports {fft_out[3]}]
set_load -pin_load 0.1 [get_ports {fft_out[2]}]
set_load -pin_load 0.1 [get_ports {fft_out[1]}]
set_load -pin_load 0.1 [get_ports {fft_out[0]}]
set_load -pin_load 0.1 [get_ports output_mode]
set_load -pin_load 0.1 [get_ports out_valid]
set_max_transition 0.08 [get_ports {fft_out[511]}]
set_max_transition 0.08 [get_ports {fft_out[510]}]
set_max_transition 0.08 [get_ports {fft_out[509]}]
set_max_transition 0.08 [get_ports {fft_out[508]}]
set_max_transition 0.08 [get_ports {fft_out[507]}]
set_max_transition 0.08 [get_ports {fft_out[506]}]
set_max_transition 0.08 [get_ports {fft_out[505]}]
set_max_transition 0.08 [get_ports {fft_out[504]}]
set_max_transition 0.08 [get_ports {fft_out[503]}]
set_max_transition 0.08 [get_ports {fft_out[502]}]
set_max_transition 0.08 [get_ports {fft_out[501]}]
set_max_transition 0.08 [get_ports {fft_out[500]}]
set_max_transition 0.08 [get_ports {fft_out[499]}]
set_max_transition 0.08 [get_ports {fft_out[498]}]
set_max_transition 0.08 [get_ports {fft_out[497]}]
set_max_transition 0.08 [get_ports {fft_out[496]}]
set_max_transition 0.08 [get_ports {fft_out[495]}]
set_max_transition 0.08 [get_ports {fft_out[494]}]
set_max_transition 0.08 [get_ports {fft_out[493]}]
set_max_transition 0.08 [get_ports {fft_out[492]}]
set_max_transition 0.08 [get_ports {fft_out[491]}]
set_max_transition 0.08 [get_ports {fft_out[490]}]
set_max_transition 0.08 [get_ports {fft_out[489]}]
set_max_transition 0.08 [get_ports {fft_out[488]}]
set_max_transition 0.08 [get_ports {fft_out[487]}]
set_max_transition 0.08 [get_ports {fft_out[486]}]
set_max_transition 0.08 [get_ports {fft_out[485]}]
set_max_transition 0.08 [get_ports {fft_out[484]}]
set_max_transition 0.08 [get_ports {fft_out[483]}]
set_max_transition 0.08 [get_ports {fft_out[482]}]
set_max_transition 0.08 [get_ports {fft_out[481]}]
set_max_transition 0.08 [get_ports {fft_out[480]}]
set_max_transition 0.08 [get_ports {fft_out[479]}]
set_max_transition 0.08 [get_ports {fft_out[478]}]
set_max_transition 0.08 [get_ports {fft_out[477]}]
set_max_transition 0.08 [get_ports {fft_out[476]}]
set_max_transition 0.08 [get_ports {fft_out[475]}]
set_max_transition 0.08 [get_ports {fft_out[474]}]
set_max_transition 0.08 [get_ports {fft_out[473]}]
set_max_transition 0.08 [get_ports {fft_out[472]}]
set_max_transition 0.08 [get_ports {fft_out[471]}]
set_max_transition 0.08 [get_ports {fft_out[470]}]
set_max_transition 0.08 [get_ports {fft_out[469]}]
set_max_transition 0.08 [get_ports {fft_out[468]}]
set_max_transition 0.08 [get_ports {fft_out[467]}]
set_max_transition 0.08 [get_ports {fft_out[466]}]
set_max_transition 0.08 [get_ports {fft_out[465]}]
set_max_transition 0.08 [get_ports {fft_out[464]}]
set_max_transition 0.08 [get_ports {fft_out[463]}]
set_max_transition 0.08 [get_ports {fft_out[462]}]
set_max_transition 0.08 [get_ports {fft_out[461]}]
set_max_transition 0.08 [get_ports {fft_out[460]}]
set_max_transition 0.08 [get_ports {fft_out[459]}]
set_max_transition 0.08 [get_ports {fft_out[458]}]
set_max_transition 0.08 [get_ports {fft_out[457]}]
set_max_transition 0.08 [get_ports {fft_out[456]}]
set_max_transition 0.08 [get_ports {fft_out[455]}]
set_max_transition 0.08 [get_ports {fft_out[454]}]
set_max_transition 0.08 [get_ports {fft_out[453]}]
set_max_transition 0.08 [get_ports {fft_out[452]}]
set_max_transition 0.08 [get_ports {fft_out[451]}]
set_max_transition 0.08 [get_ports {fft_out[450]}]
set_max_transition 0.08 [get_ports {fft_out[449]}]
set_max_transition 0.08 [get_ports {fft_out[448]}]
set_max_transition 0.08 [get_ports {fft_out[447]}]
set_max_transition 0.08 [get_ports {fft_out[446]}]
set_max_transition 0.08 [get_ports {fft_out[445]}]
set_max_transition 0.08 [get_ports {fft_out[444]}]
set_max_transition 0.08 [get_ports {fft_out[443]}]
set_max_transition 0.08 [get_ports {fft_out[442]}]
set_max_transition 0.08 [get_ports {fft_out[441]}]
set_max_transition 0.08 [get_ports {fft_out[440]}]
set_max_transition 0.08 [get_ports {fft_out[439]}]
set_max_transition 0.08 [get_ports {fft_out[438]}]
set_max_transition 0.08 [get_ports {fft_out[437]}]
set_max_transition 0.08 [get_ports {fft_out[436]}]
set_max_transition 0.08 [get_ports {fft_out[435]}]
set_max_transition 0.08 [get_ports {fft_out[434]}]
set_max_transition 0.08 [get_ports {fft_out[433]}]
set_max_transition 0.08 [get_ports {fft_out[432]}]
set_max_transition 0.08 [get_ports {fft_out[431]}]
set_max_transition 0.08 [get_ports {fft_out[430]}]
set_max_transition 0.08 [get_ports {fft_out[429]}]
set_max_transition 0.08 [get_ports {fft_out[428]}]
set_max_transition 0.08 [get_ports {fft_out[427]}]
set_max_transition 0.08 [get_ports {fft_out[426]}]
set_max_transition 0.08 [get_ports {fft_out[425]}]
set_max_transition 0.08 [get_ports {fft_out[424]}]
set_max_transition 0.08 [get_ports {fft_out[423]}]
set_max_transition 0.08 [get_ports {fft_out[422]}]
set_max_transition 0.08 [get_ports {fft_out[421]}]
set_max_transition 0.08 [get_ports {fft_out[420]}]
set_max_transition 0.08 [get_ports {fft_out[419]}]
set_max_transition 0.08 [get_ports {fft_out[418]}]
set_max_transition 0.08 [get_ports {fft_out[417]}]
set_max_transition 0.08 [get_ports {fft_out[416]}]
set_max_transition 0.08 [get_ports {fft_out[415]}]
set_max_transition 0.08 [get_ports {fft_out[414]}]
set_max_transition 0.08 [get_ports {fft_out[413]}]
set_max_transition 0.08 [get_ports {fft_out[412]}]
set_max_transition 0.08 [get_ports {fft_out[411]}]
set_max_transition 0.08 [get_ports {fft_out[410]}]
set_max_transition 0.08 [get_ports {fft_out[409]}]
set_max_transition 0.08 [get_ports {fft_out[408]}]
set_max_transition 0.08 [get_ports {fft_out[407]}]
set_max_transition 0.08 [get_ports {fft_out[406]}]
set_max_transition 0.08 [get_ports {fft_out[405]}]
set_max_transition 0.08 [get_ports {fft_out[404]}]
set_max_transition 0.08 [get_ports {fft_out[403]}]
set_max_transition 0.08 [get_ports {fft_out[402]}]
set_max_transition 0.08 [get_ports {fft_out[401]}]
set_max_transition 0.08 [get_ports {fft_out[400]}]
set_max_transition 0.08 [get_ports {fft_out[399]}]
set_max_transition 0.08 [get_ports {fft_out[398]}]
set_max_transition 0.08 [get_ports {fft_out[397]}]
set_max_transition 0.08 [get_ports {fft_out[396]}]
set_max_transition 0.08 [get_ports {fft_out[395]}]
set_max_transition 0.08 [get_ports {fft_out[394]}]
set_max_transition 0.08 [get_ports {fft_out[393]}]
set_max_transition 0.08 [get_ports {fft_out[392]}]
set_max_transition 0.08 [get_ports {fft_out[391]}]
set_max_transition 0.08 [get_ports {fft_out[390]}]
set_max_transition 0.08 [get_ports {fft_out[389]}]
set_max_transition 0.08 [get_ports {fft_out[388]}]
set_max_transition 0.08 [get_ports {fft_out[387]}]
set_max_transition 0.08 [get_ports {fft_out[386]}]
set_max_transition 0.08 [get_ports {fft_out[385]}]
set_max_transition 0.08 [get_ports {fft_out[384]}]
set_max_transition 0.08 [get_ports {fft_out[383]}]
set_max_transition 0.08 [get_ports {fft_out[382]}]
set_max_transition 0.08 [get_ports {fft_out[381]}]
set_max_transition 0.08 [get_ports {fft_out[380]}]
set_max_transition 0.08 [get_ports {fft_out[379]}]
set_max_transition 0.08 [get_ports {fft_out[378]}]
set_max_transition 0.08 [get_ports {fft_out[377]}]
set_max_transition 0.08 [get_ports {fft_out[376]}]
set_max_transition 0.08 [get_ports {fft_out[375]}]
set_max_transition 0.08 [get_ports {fft_out[374]}]
set_max_transition 0.08 [get_ports {fft_out[373]}]
set_max_transition 0.08 [get_ports {fft_out[372]}]
set_max_transition 0.08 [get_ports {fft_out[371]}]
set_max_transition 0.08 [get_ports {fft_out[370]}]
set_max_transition 0.08 [get_ports {fft_out[369]}]
set_max_transition 0.08 [get_ports {fft_out[368]}]
set_max_transition 0.08 [get_ports {fft_out[367]}]
set_max_transition 0.08 [get_ports {fft_out[366]}]
set_max_transition 0.08 [get_ports {fft_out[365]}]
set_max_transition 0.08 [get_ports {fft_out[364]}]
set_max_transition 0.08 [get_ports {fft_out[363]}]
set_max_transition 0.08 [get_ports {fft_out[362]}]
set_max_transition 0.08 [get_ports {fft_out[361]}]
set_max_transition 0.08 [get_ports {fft_out[360]}]
set_max_transition 0.08 [get_ports {fft_out[359]}]
set_max_transition 0.08 [get_ports {fft_out[358]}]
set_max_transition 0.08 [get_ports {fft_out[357]}]
set_max_transition 0.08 [get_ports {fft_out[356]}]
set_max_transition 0.08 [get_ports {fft_out[355]}]
set_max_transition 0.08 [get_ports {fft_out[354]}]
set_max_transition 0.08 [get_ports {fft_out[353]}]
set_max_transition 0.08 [get_ports {fft_out[352]}]
set_max_transition 0.08 [get_ports {fft_out[351]}]
set_max_transition 0.08 [get_ports {fft_out[350]}]
set_max_transition 0.08 [get_ports {fft_out[349]}]
set_max_transition 0.08 [get_ports {fft_out[348]}]
set_max_transition 0.08 [get_ports {fft_out[347]}]
set_max_transition 0.08 [get_ports {fft_out[346]}]
set_max_transition 0.08 [get_ports {fft_out[345]}]
set_max_transition 0.08 [get_ports {fft_out[344]}]
set_max_transition 0.08 [get_ports {fft_out[343]}]
set_max_transition 0.08 [get_ports {fft_out[342]}]
set_max_transition 0.08 [get_ports {fft_out[341]}]
set_max_transition 0.08 [get_ports {fft_out[340]}]
set_max_transition 0.08 [get_ports {fft_out[339]}]
set_max_transition 0.08 [get_ports {fft_out[338]}]
set_max_transition 0.08 [get_ports {fft_out[337]}]
set_max_transition 0.08 [get_ports {fft_out[336]}]
set_max_transition 0.08 [get_ports {fft_out[335]}]
set_max_transition 0.08 [get_ports {fft_out[334]}]
set_max_transition 0.08 [get_ports {fft_out[333]}]
set_max_transition 0.08 [get_ports {fft_out[332]}]
set_max_transition 0.08 [get_ports {fft_out[331]}]
set_max_transition 0.08 [get_ports {fft_out[330]}]
set_max_transition 0.08 [get_ports {fft_out[329]}]
set_max_transition 0.08 [get_ports {fft_out[328]}]
set_max_transition 0.08 [get_ports {fft_out[327]}]
set_max_transition 0.08 [get_ports {fft_out[326]}]
set_max_transition 0.08 [get_ports {fft_out[325]}]
set_max_transition 0.08 [get_ports {fft_out[324]}]
set_max_transition 0.08 [get_ports {fft_out[323]}]
set_max_transition 0.08 [get_ports {fft_out[322]}]
set_max_transition 0.08 [get_ports {fft_out[321]}]
set_max_transition 0.08 [get_ports {fft_out[320]}]
set_max_transition 0.08 [get_ports {fft_out[319]}]
set_max_transition 0.08 [get_ports {fft_out[318]}]
set_max_transition 0.08 [get_ports {fft_out[317]}]
set_max_transition 0.08 [get_ports {fft_out[316]}]
set_max_transition 0.08 [get_ports {fft_out[315]}]
set_max_transition 0.08 [get_ports {fft_out[314]}]
set_max_transition 0.08 [get_ports {fft_out[313]}]
set_max_transition 0.08 [get_ports {fft_out[312]}]
set_max_transition 0.08 [get_ports {fft_out[311]}]
set_max_transition 0.08 [get_ports {fft_out[310]}]
set_max_transition 0.08 [get_ports {fft_out[309]}]
set_max_transition 0.08 [get_ports {fft_out[308]}]
set_max_transition 0.08 [get_ports {fft_out[307]}]
set_max_transition 0.08 [get_ports {fft_out[306]}]
set_max_transition 0.08 [get_ports {fft_out[305]}]
set_max_transition 0.08 [get_ports {fft_out[304]}]
set_max_transition 0.08 [get_ports {fft_out[303]}]
set_max_transition 0.08 [get_ports {fft_out[302]}]
set_max_transition 0.08 [get_ports {fft_out[301]}]
set_max_transition 0.08 [get_ports {fft_out[300]}]
set_max_transition 0.08 [get_ports {fft_out[299]}]
set_max_transition 0.08 [get_ports {fft_out[298]}]
set_max_transition 0.08 [get_ports {fft_out[297]}]
set_max_transition 0.08 [get_ports {fft_out[296]}]
set_max_transition 0.08 [get_ports {fft_out[295]}]
set_max_transition 0.08 [get_ports {fft_out[294]}]
set_max_transition 0.08 [get_ports {fft_out[293]}]
set_max_transition 0.08 [get_ports {fft_out[292]}]
set_max_transition 0.08 [get_ports {fft_out[291]}]
set_max_transition 0.08 [get_ports {fft_out[290]}]
set_max_transition 0.08 [get_ports {fft_out[289]}]
set_max_transition 0.08 [get_ports {fft_out[288]}]
set_max_transition 0.08 [get_ports {fft_out[287]}]
set_max_transition 0.08 [get_ports {fft_out[286]}]
set_max_transition 0.08 [get_ports {fft_out[285]}]
set_max_transition 0.08 [get_ports {fft_out[284]}]
set_max_transition 0.08 [get_ports {fft_out[283]}]
set_max_transition 0.08 [get_ports {fft_out[282]}]
set_max_transition 0.08 [get_ports {fft_out[281]}]
set_max_transition 0.08 [get_ports {fft_out[280]}]
set_max_transition 0.08 [get_ports {fft_out[279]}]
set_max_transition 0.08 [get_ports {fft_out[278]}]
set_max_transition 0.08 [get_ports {fft_out[277]}]
set_max_transition 0.08 [get_ports {fft_out[276]}]
set_max_transition 0.08 [get_ports {fft_out[275]}]
set_max_transition 0.08 [get_ports {fft_out[274]}]
set_max_transition 0.08 [get_ports {fft_out[273]}]
set_max_transition 0.08 [get_ports {fft_out[272]}]
set_max_transition 0.08 [get_ports {fft_out[271]}]
set_max_transition 0.08 [get_ports {fft_out[270]}]
set_max_transition 0.08 [get_ports {fft_out[269]}]
set_max_transition 0.08 [get_ports {fft_out[268]}]
set_max_transition 0.08 [get_ports {fft_out[267]}]
set_max_transition 0.08 [get_ports {fft_out[266]}]
set_max_transition 0.08 [get_ports {fft_out[265]}]
set_max_transition 0.08 [get_ports {fft_out[264]}]
set_max_transition 0.08 [get_ports {fft_out[263]}]
set_max_transition 0.08 [get_ports {fft_out[262]}]
set_max_transition 0.08 [get_ports {fft_out[261]}]
set_max_transition 0.08 [get_ports {fft_out[260]}]
set_max_transition 0.08 [get_ports {fft_out[259]}]
set_max_transition 0.08 [get_ports {fft_out[258]}]
set_max_transition 0.08 [get_ports {fft_out[257]}]
set_max_transition 0.08 [get_ports {fft_out[256]}]
set_max_transition 0.08 [get_ports {fft_out[255]}]
set_max_transition 0.08 [get_ports {fft_out[254]}]
set_max_transition 0.08 [get_ports {fft_out[253]}]
set_max_transition 0.08 [get_ports {fft_out[252]}]
set_max_transition 0.08 [get_ports {fft_out[251]}]
set_max_transition 0.08 [get_ports {fft_out[250]}]
set_max_transition 0.08 [get_ports {fft_out[249]}]
set_max_transition 0.08 [get_ports {fft_out[248]}]
set_max_transition 0.08 [get_ports {fft_out[247]}]
set_max_transition 0.08 [get_ports {fft_out[246]}]
set_max_transition 0.08 [get_ports {fft_out[245]}]
set_max_transition 0.08 [get_ports {fft_out[244]}]
set_max_transition 0.08 [get_ports {fft_out[243]}]
set_max_transition 0.08 [get_ports {fft_out[242]}]
set_max_transition 0.08 [get_ports {fft_out[241]}]
set_max_transition 0.08 [get_ports {fft_out[240]}]
set_max_transition 0.08 [get_ports {fft_out[239]}]
set_max_transition 0.08 [get_ports {fft_out[238]}]
set_max_transition 0.08 [get_ports {fft_out[237]}]
set_max_transition 0.08 [get_ports {fft_out[236]}]
set_max_transition 0.08 [get_ports {fft_out[235]}]
set_max_transition 0.08 [get_ports {fft_out[234]}]
set_max_transition 0.08 [get_ports {fft_out[233]}]
set_max_transition 0.08 [get_ports {fft_out[232]}]
set_max_transition 0.08 [get_ports {fft_out[231]}]
set_max_transition 0.08 [get_ports {fft_out[230]}]
set_max_transition 0.08 [get_ports {fft_out[229]}]
set_max_transition 0.08 [get_ports {fft_out[228]}]
set_max_transition 0.08 [get_ports {fft_out[227]}]
set_max_transition 0.08 [get_ports {fft_out[226]}]
set_max_transition 0.08 [get_ports {fft_out[225]}]
set_max_transition 0.08 [get_ports {fft_out[224]}]
set_max_transition 0.08 [get_ports {fft_out[223]}]
set_max_transition 0.08 [get_ports {fft_out[222]}]
set_max_transition 0.08 [get_ports {fft_out[221]}]
set_max_transition 0.08 [get_ports {fft_out[220]}]
set_max_transition 0.08 [get_ports {fft_out[219]}]
set_max_transition 0.08 [get_ports {fft_out[218]}]
set_max_transition 0.08 [get_ports {fft_out[217]}]
set_max_transition 0.08 [get_ports {fft_out[216]}]
set_max_transition 0.08 [get_ports {fft_out[215]}]
set_max_transition 0.08 [get_ports {fft_out[214]}]
set_max_transition 0.08 [get_ports {fft_out[213]}]
set_max_transition 0.08 [get_ports {fft_out[212]}]
set_max_transition 0.08 [get_ports {fft_out[211]}]
set_max_transition 0.08 [get_ports {fft_out[210]}]
set_max_transition 0.08 [get_ports {fft_out[209]}]
set_max_transition 0.08 [get_ports {fft_out[208]}]
set_max_transition 0.08 [get_ports {fft_out[207]}]
set_max_transition 0.08 [get_ports {fft_out[206]}]
set_max_transition 0.08 [get_ports {fft_out[205]}]
set_max_transition 0.08 [get_ports {fft_out[204]}]
set_max_transition 0.08 [get_ports {fft_out[203]}]
set_max_transition 0.08 [get_ports {fft_out[202]}]
set_max_transition 0.08 [get_ports {fft_out[201]}]
set_max_transition 0.08 [get_ports {fft_out[200]}]
set_max_transition 0.08 [get_ports {fft_out[199]}]
set_max_transition 0.08 [get_ports {fft_out[198]}]
set_max_transition 0.08 [get_ports {fft_out[197]}]
set_max_transition 0.08 [get_ports {fft_out[196]}]
set_max_transition 0.08 [get_ports {fft_out[195]}]
set_max_transition 0.08 [get_ports {fft_out[194]}]
set_max_transition 0.08 [get_ports {fft_out[193]}]
set_max_transition 0.08 [get_ports {fft_out[192]}]
set_max_transition 0.08 [get_ports {fft_out[191]}]
set_max_transition 0.08 [get_ports {fft_out[190]}]
set_max_transition 0.08 [get_ports {fft_out[189]}]
set_max_transition 0.08 [get_ports {fft_out[188]}]
set_max_transition 0.08 [get_ports {fft_out[187]}]
set_max_transition 0.08 [get_ports {fft_out[186]}]
set_max_transition 0.08 [get_ports {fft_out[185]}]
set_max_transition 0.08 [get_ports {fft_out[184]}]
set_max_transition 0.08 [get_ports {fft_out[183]}]
set_max_transition 0.08 [get_ports {fft_out[182]}]
set_max_transition 0.08 [get_ports {fft_out[181]}]
set_max_transition 0.08 [get_ports {fft_out[180]}]
set_max_transition 0.08 [get_ports {fft_out[179]}]
set_max_transition 0.08 [get_ports {fft_out[178]}]
set_max_transition 0.08 [get_ports {fft_out[177]}]
set_max_transition 0.08 [get_ports {fft_out[176]}]
set_max_transition 0.08 [get_ports {fft_out[175]}]
set_max_transition 0.08 [get_ports {fft_out[174]}]
set_max_transition 0.08 [get_ports {fft_out[173]}]
set_max_transition 0.08 [get_ports {fft_out[172]}]
set_max_transition 0.08 [get_ports {fft_out[171]}]
set_max_transition 0.08 [get_ports {fft_out[170]}]
set_max_transition 0.08 [get_ports {fft_out[169]}]
set_max_transition 0.08 [get_ports {fft_out[168]}]
set_max_transition 0.08 [get_ports {fft_out[167]}]
set_max_transition 0.08 [get_ports {fft_out[166]}]
set_max_transition 0.08 [get_ports {fft_out[165]}]
set_max_transition 0.08 [get_ports {fft_out[164]}]
set_max_transition 0.08 [get_ports {fft_out[163]}]
set_max_transition 0.08 [get_ports {fft_out[162]}]
set_max_transition 0.08 [get_ports {fft_out[161]}]
set_max_transition 0.08 [get_ports {fft_out[160]}]
set_max_transition 0.08 [get_ports {fft_out[159]}]
set_max_transition 0.08 [get_ports {fft_out[158]}]
set_max_transition 0.08 [get_ports {fft_out[157]}]
set_max_transition 0.08 [get_ports {fft_out[156]}]
set_max_transition 0.08 [get_ports {fft_out[155]}]
set_max_transition 0.08 [get_ports {fft_out[154]}]
set_max_transition 0.08 [get_ports {fft_out[153]}]
set_max_transition 0.08 [get_ports {fft_out[152]}]
set_max_transition 0.08 [get_ports {fft_out[151]}]
set_max_transition 0.08 [get_ports {fft_out[150]}]
set_max_transition 0.08 [get_ports {fft_out[149]}]
set_max_transition 0.08 [get_ports {fft_out[148]}]
set_max_transition 0.08 [get_ports {fft_out[147]}]
set_max_transition 0.08 [get_ports {fft_out[146]}]
set_max_transition 0.08 [get_ports {fft_out[145]}]
set_max_transition 0.08 [get_ports {fft_out[144]}]
set_max_transition 0.08 [get_ports {fft_out[143]}]
set_max_transition 0.08 [get_ports {fft_out[142]}]
set_max_transition 0.08 [get_ports {fft_out[141]}]
set_max_transition 0.08 [get_ports {fft_out[140]}]
set_max_transition 0.08 [get_ports {fft_out[139]}]
set_max_transition 0.08 [get_ports {fft_out[138]}]
set_max_transition 0.08 [get_ports {fft_out[137]}]
set_max_transition 0.08 [get_ports {fft_out[136]}]
set_max_transition 0.08 [get_ports {fft_out[135]}]
set_max_transition 0.08 [get_ports {fft_out[134]}]
set_max_transition 0.08 [get_ports {fft_out[133]}]
set_max_transition 0.08 [get_ports {fft_out[132]}]
set_max_transition 0.08 [get_ports {fft_out[131]}]
set_max_transition 0.08 [get_ports {fft_out[130]}]
set_max_transition 0.08 [get_ports {fft_out[129]}]
set_max_transition 0.08 [get_ports {fft_out[128]}]
set_max_transition 0.08 [get_ports {fft_out[127]}]
set_max_transition 0.08 [get_ports {fft_out[126]}]
set_max_transition 0.08 [get_ports {fft_out[125]}]
set_max_transition 0.08 [get_ports {fft_out[124]}]
set_max_transition 0.08 [get_ports {fft_out[123]}]
set_max_transition 0.08 [get_ports {fft_out[122]}]
set_max_transition 0.08 [get_ports {fft_out[121]}]
set_max_transition 0.08 [get_ports {fft_out[120]}]
set_max_transition 0.08 [get_ports {fft_out[119]}]
set_max_transition 0.08 [get_ports {fft_out[118]}]
set_max_transition 0.08 [get_ports {fft_out[117]}]
set_max_transition 0.08 [get_ports {fft_out[116]}]
set_max_transition 0.08 [get_ports {fft_out[115]}]
set_max_transition 0.08 [get_ports {fft_out[114]}]
set_max_transition 0.08 [get_ports {fft_out[113]}]
set_max_transition 0.08 [get_ports {fft_out[112]}]
set_max_transition 0.08 [get_ports {fft_out[111]}]
set_max_transition 0.08 [get_ports {fft_out[110]}]
set_max_transition 0.08 [get_ports {fft_out[109]}]
set_max_transition 0.08 [get_ports {fft_out[108]}]
set_max_transition 0.08 [get_ports {fft_out[107]}]
set_max_transition 0.08 [get_ports {fft_out[106]}]
set_max_transition 0.08 [get_ports {fft_out[105]}]
set_max_transition 0.08 [get_ports {fft_out[104]}]
set_max_transition 0.08 [get_ports {fft_out[103]}]
set_max_transition 0.08 [get_ports {fft_out[102]}]
set_max_transition 0.08 [get_ports {fft_out[101]}]
set_max_transition 0.08 [get_ports {fft_out[100]}]
set_max_transition 0.08 [get_ports {fft_out[99]}]
set_max_transition 0.08 [get_ports {fft_out[98]}]
set_max_transition 0.08 [get_ports {fft_out[97]}]
set_max_transition 0.08 [get_ports {fft_out[96]}]
set_max_transition 0.08 [get_ports {fft_out[95]}]
set_max_transition 0.08 [get_ports {fft_out[94]}]
set_max_transition 0.08 [get_ports {fft_out[93]}]
set_max_transition 0.08 [get_ports {fft_out[92]}]
set_max_transition 0.08 [get_ports {fft_out[91]}]
set_max_transition 0.08 [get_ports {fft_out[90]}]
set_max_transition 0.08 [get_ports {fft_out[89]}]
set_max_transition 0.08 [get_ports {fft_out[88]}]
set_max_transition 0.08 [get_ports {fft_out[87]}]
set_max_transition 0.08 [get_ports {fft_out[86]}]
set_max_transition 0.08 [get_ports {fft_out[85]}]
set_max_transition 0.08 [get_ports {fft_out[84]}]
set_max_transition 0.08 [get_ports {fft_out[83]}]
set_max_transition 0.08 [get_ports {fft_out[82]}]
set_max_transition 0.08 [get_ports {fft_out[81]}]
set_max_transition 0.08 [get_ports {fft_out[80]}]
set_max_transition 0.08 [get_ports {fft_out[79]}]
set_max_transition 0.08 [get_ports {fft_out[78]}]
set_max_transition 0.08 [get_ports {fft_out[77]}]
set_max_transition 0.08 [get_ports {fft_out[76]}]
set_max_transition 0.08 [get_ports {fft_out[75]}]
set_max_transition 0.08 [get_ports {fft_out[74]}]
set_max_transition 0.08 [get_ports {fft_out[73]}]
set_max_transition 0.08 [get_ports {fft_out[72]}]
set_max_transition 0.08 [get_ports {fft_out[71]}]
set_max_transition 0.08 [get_ports {fft_out[70]}]
set_max_transition 0.08 [get_ports {fft_out[69]}]
set_max_transition 0.08 [get_ports {fft_out[68]}]
set_max_transition 0.08 [get_ports {fft_out[67]}]
set_max_transition 0.08 [get_ports {fft_out[66]}]
set_max_transition 0.08 [get_ports {fft_out[65]}]
set_max_transition 0.08 [get_ports {fft_out[64]}]
set_max_transition 0.08 [get_ports {fft_out[63]}]
set_max_transition 0.08 [get_ports {fft_out[62]}]
set_max_transition 0.08 [get_ports {fft_out[61]}]
set_max_transition 0.08 [get_ports {fft_out[60]}]
set_max_transition 0.08 [get_ports {fft_out[59]}]
set_max_transition 0.08 [get_ports {fft_out[58]}]
set_max_transition 0.08 [get_ports {fft_out[57]}]
set_max_transition 0.08 [get_ports {fft_out[56]}]
set_max_transition 0.08 [get_ports {fft_out[55]}]
set_max_transition 0.08 [get_ports {fft_out[54]}]
set_max_transition 0.08 [get_ports {fft_out[53]}]
set_max_transition 0.08 [get_ports {fft_out[52]}]
set_max_transition 0.08 [get_ports {fft_out[51]}]
set_max_transition 0.08 [get_ports {fft_out[50]}]
set_max_transition 0.08 [get_ports {fft_out[49]}]
set_max_transition 0.08 [get_ports {fft_out[48]}]
set_max_transition 0.08 [get_ports {fft_out[47]}]
set_max_transition 0.08 [get_ports {fft_out[46]}]
set_max_transition 0.08 [get_ports {fft_out[45]}]
set_max_transition 0.08 [get_ports {fft_out[44]}]
set_max_transition 0.08 [get_ports {fft_out[43]}]
set_max_transition 0.08 [get_ports {fft_out[42]}]
set_max_transition 0.08 [get_ports {fft_out[41]}]
set_max_transition 0.08 [get_ports {fft_out[40]}]
set_max_transition 0.08 [get_ports {fft_out[39]}]
set_max_transition 0.08 [get_ports {fft_out[38]}]
set_max_transition 0.08 [get_ports {fft_out[37]}]
set_max_transition 0.08 [get_ports {fft_out[36]}]
set_max_transition 0.08 [get_ports {fft_out[35]}]
set_max_transition 0.08 [get_ports {fft_out[34]}]
set_max_transition 0.08 [get_ports {fft_out[33]}]
set_max_transition 0.08 [get_ports {fft_out[32]}]
set_max_transition 0.08 [get_ports {fft_out[31]}]
set_max_transition 0.08 [get_ports {fft_out[30]}]
set_max_transition 0.08 [get_ports {fft_out[29]}]
set_max_transition 0.08 [get_ports {fft_out[28]}]
set_max_transition 0.08 [get_ports {fft_out[27]}]
set_max_transition 0.08 [get_ports {fft_out[26]}]
set_max_transition 0.08 [get_ports {fft_out[25]}]
set_max_transition 0.08 [get_ports {fft_out[24]}]
set_max_transition 0.08 [get_ports {fft_out[23]}]
set_max_transition 0.08 [get_ports {fft_out[22]}]
set_max_transition 0.08 [get_ports {fft_out[21]}]
set_max_transition 0.08 [get_ports {fft_out[20]}]
set_max_transition 0.08 [get_ports {fft_out[19]}]
set_max_transition 0.08 [get_ports {fft_out[18]}]
set_max_transition 0.08 [get_ports {fft_out[17]}]
set_max_transition 0.08 [get_ports {fft_out[16]}]
set_max_transition 0.08 [get_ports {fft_out[15]}]
set_max_transition 0.08 [get_ports {fft_out[14]}]
set_max_transition 0.08 [get_ports {fft_out[13]}]
set_max_transition 0.08 [get_ports {fft_out[12]}]
set_max_transition 0.08 [get_ports {fft_out[11]}]
set_max_transition 0.08 [get_ports {fft_out[10]}]
set_max_transition 0.08 [get_ports {fft_out[9]}]
set_max_transition 0.08 [get_ports {fft_out[8]}]
set_max_transition 0.08 [get_ports {fft_out[7]}]
set_max_transition 0.08 [get_ports {fft_out[6]}]
set_max_transition 0.08 [get_ports {fft_out[5]}]
set_max_transition 0.08 [get_ports {fft_out[4]}]
set_max_transition 0.08 [get_ports {fft_out[3]}]
set_max_transition 0.08 [get_ports {fft_out[2]}]
set_max_transition 0.08 [get_ports {fft_out[1]}]
set_max_transition 0.08 [get_ports {fft_out[0]}]
set_max_transition 0.08 [get_ports output_mode]
set_max_transition 0.08 [get_ports out_valid]
create_clock [get_ports clk]  -name core_clk  -period 14  -waveform {0 7}
set_clock_latency 0.1  [get_clocks core_clk]
set_clock_uncertainty 0.35  [get_clocks core_clk]
set_clock_transition -max -rise 0.08 [get_clocks core_clk]
set_clock_transition -max -fall 0.08 [get_clocks core_clk]
set_clock_transition -min -rise 0.08 [get_clocks core_clk]
set_clock_transition -min -fall 0.08 [get_clocks core_clk]
group_path -name FEEDTHROUGH  -from [list [get_ports reset] [get_ports enable] [get_ports {data_in_0[63]}] [get_ports {data_in_0[62]}] [get_ports {data_in_0[61]}] [get_ports {data_in_0[60]}] [get_ports {data_in_0[59]}] [get_ports {data_in_0[58]}] [get_ports {data_in_0[57]}] [get_ports {data_in_0[56]}] [get_ports {data_in_0[55]}] [get_ports {data_in_0[54]}] [get_ports {data_in_0[53]}] [get_ports {data_in_0[52]}] [get_ports {data_in_0[51]}] [get_ports {data_in_0[50]}] [get_ports {data_in_0[49]}] [get_ports {data_in_0[48]}] [get_ports {data_in_0[47]}] [get_ports {data_in_0[46]}] [get_ports {data_in_0[45]}] [get_ports {data_in_0[44]}] [get_ports {data_in_0[43]}] [get_ports {data_in_0[42]}] [get_ports {data_in_0[41]}] [get_ports {data_in_0[40]}] [get_ports {data_in_0[39]}] [get_ports {data_in_0[38]}] [get_ports {data_in_0[37]}] [get_ports {data_in_0[36]}] [get_ports {data_in_0[35]}] [get_ports {data_in_0[34]}] [get_ports {data_in_0[33]}] [get_ports {data_in_0[32]}] [get_ports {data_in_0[31]}] [get_ports {data_in_0[30]}] [get_ports {data_in_0[29]}] [get_ports {data_in_0[28]}] [get_ports {data_in_0[27]}] [get_ports {data_in_0[26]}] [get_ports {data_in_0[25]}] [get_ports {data_in_0[24]}] [get_ports {data_in_0[23]}] [get_ports {data_in_0[22]}] [get_ports {data_in_0[21]}] [get_ports {data_in_0[20]}] [get_ports {data_in_0[19]}] [get_ports {data_in_0[18]}] [get_ports {data_in_0[17]}] [get_ports {data_in_0[16]}] [get_ports {data_in_0[15]}] [get_ports {data_in_0[14]}] [get_ports {data_in_0[13]}] [get_ports {data_in_0[12]}] [get_ports {data_in_0[11]}] [get_ports {data_in_0[10]}] [get_ports {data_in_0[9]}] [get_ports {data_in_0[8]}] [get_ports {data_in_0[7]}] [get_ports {data_in_0[6]}] [get_ports {data_in_0[5]}] [get_ports {data_in_0[4]}] [get_ports {data_in_0[3]}] [get_ports {data_in_0[2]}] [get_ports {data_in_0[1]}] [get_ports {data_in_0[0]}] [get_ports {data_in_1[63]}] [get_ports {data_in_1[62]}] [get_ports {data_in_1[61]}] [get_ports {data_in_1[60]}] [get_ports {data_in_1[59]}] [get_ports {data_in_1[58]}] [get_ports {data_in_1[57]}] [get_ports {data_in_1[56]}] [get_ports {data_in_1[55]}] [get_ports {data_in_1[54]}] [get_ports {data_in_1[53]}] [get_ports {data_in_1[52]}] [get_ports {data_in_1[51]}] [get_ports {data_in_1[50]}] [get_ports {data_in_1[49]}] [get_ports {data_in_1[48]}] [get_ports {data_in_1[47]}] [get_ports {data_in_1[46]}] [get_ports {data_in_1[45]}] [get_ports {data_in_1[44]}] [get_ports {data_in_1[43]}] [get_ports {data_in_1[42]}] [get_ports {data_in_1[41]}] [get_ports {data_in_1[40]}] [get_ports {data_in_1[39]}] [get_ports {data_in_1[38]}] [get_ports {data_in_1[37]}] [get_ports {data_in_1[36]}] [get_ports {data_in_1[35]}] [get_ports {data_in_1[34]}] [get_ports {data_in_1[33]}] [get_ports {data_in_1[32]}] [get_ports {data_in_1[31]}] [get_ports {data_in_1[30]}] [get_ports {data_in_1[29]}] [get_ports {data_in_1[28]}] [get_ports {data_in_1[27]}] [get_ports {data_in_1[26]}] [get_ports {data_in_1[25]}] [get_ports {data_in_1[24]}] [get_ports {data_in_1[23]}] [get_ports {data_in_1[22]}] [get_ports {data_in_1[21]}] [get_ports {data_in_1[20]}] [get_ports {data_in_1[19]}] [get_ports {data_in_1[18]}] [get_ports {data_in_1[17]}] [get_ports {data_in_1[16]}] [get_ports {data_in_1[15]}] [get_ports {data_in_1[14]}] [get_ports {data_in_1[13]}] [get_ports {data_in_1[12]}] [get_ports {data_in_1[11]}] [get_ports {data_in_1[10]}] [get_ports {data_in_1[9]}] [get_ports {data_in_1[8]}] [get_ports {data_in_1[7]}] [get_ports {data_in_1[6]}] [get_ports {data_in_1[5]}] [get_ports {data_in_1[4]}] [get_ports {data_in_1[3]}] [get_ports {data_in_1[2]}] [get_ports {data_in_1[1]}] [get_ports {data_in_1[0]}]]  -to [list [get_ports {fft_out[511]}] [get_ports {fft_out[510]}] [get_ports {fft_out[509]}] [get_ports {fft_out[508]}] [get_ports {fft_out[507]}] [get_ports {fft_out[506]}] [get_ports {fft_out[505]}] [get_ports {fft_out[504]}] [get_ports {fft_out[503]}] [get_ports {fft_out[502]}] [get_ports {fft_out[501]}] [get_ports {fft_out[500]}] [get_ports {fft_out[499]}] [get_ports {fft_out[498]}] [get_ports {fft_out[497]}] [get_ports {fft_out[496]}] [get_ports {fft_out[495]}] [get_ports {fft_out[494]}] [get_ports {fft_out[493]}] [get_ports {fft_out[492]}] [get_ports {fft_out[491]}] [get_ports {fft_out[490]}] [get_ports {fft_out[489]}] [get_ports {fft_out[488]}] [get_ports {fft_out[487]}] [get_ports {fft_out[486]}] [get_ports {fft_out[485]}] [get_ports {fft_out[484]}] [get_ports {fft_out[483]}] [get_ports {fft_out[482]}] [get_ports {fft_out[481]}] [get_ports {fft_out[480]}] [get_ports {fft_out[479]}] [get_ports {fft_out[478]}] [get_ports {fft_out[477]}] [get_ports {fft_out[476]}] [get_ports {fft_out[475]}] [get_ports {fft_out[474]}] [get_ports {fft_out[473]}] [get_ports {fft_out[472]}] [get_ports {fft_out[471]}] [get_ports {fft_out[470]}] [get_ports {fft_out[469]}] [get_ports {fft_out[468]}] [get_ports {fft_out[467]}] [get_ports {fft_out[466]}] [get_ports {fft_out[465]}] [get_ports {fft_out[464]}] [get_ports {fft_out[463]}] [get_ports {fft_out[462]}] [get_ports {fft_out[461]}] [get_ports {fft_out[460]}] [get_ports {fft_out[459]}] [get_ports {fft_out[458]}] [get_ports {fft_out[457]}] [get_ports {fft_out[456]}] [get_ports {fft_out[455]}] [get_ports {fft_out[454]}] [get_ports {fft_out[453]}] [get_ports {fft_out[452]}] [get_ports {fft_out[451]}] [get_ports {fft_out[450]}] [get_ports {fft_out[449]}] [get_ports {fft_out[448]}] [get_ports {fft_out[447]}] [get_ports {fft_out[446]}] [get_ports {fft_out[445]}] [get_ports {fft_out[444]}] [get_ports {fft_out[443]}] [get_ports {fft_out[442]}] [get_ports {fft_out[441]}] [get_ports {fft_out[440]}] [get_ports {fft_out[439]}] [get_ports {fft_out[438]}] [get_ports {fft_out[437]}] [get_ports {fft_out[436]}] [get_ports {fft_out[435]}] [get_ports {fft_out[434]}] [get_ports {fft_out[433]}] [get_ports {fft_out[432]}] [get_ports {fft_out[431]}] [get_ports {fft_out[430]}] [get_ports {fft_out[429]}] [get_ports {fft_out[428]}] [get_ports {fft_out[427]}] [get_ports {fft_out[426]}] [get_ports {fft_out[425]}] [get_ports {fft_out[424]}] [get_ports {fft_out[423]}] [get_ports {fft_out[422]}] [get_ports {fft_out[421]}] [get_ports {fft_out[420]}] [get_ports {fft_out[419]}] [get_ports {fft_out[418]}] [get_ports {fft_out[417]}] [get_ports {fft_out[416]}] [get_ports {fft_out[415]}] [get_ports {fft_out[414]}] [get_ports {fft_out[413]}] [get_ports {fft_out[412]}] [get_ports {fft_out[411]}] [get_ports {fft_out[410]}] [get_ports {fft_out[409]}] [get_ports {fft_out[408]}] [get_ports {fft_out[407]}] [get_ports {fft_out[406]}] [get_ports {fft_out[405]}] [get_ports {fft_out[404]}] [get_ports {fft_out[403]}] [get_ports {fft_out[402]}] [get_ports {fft_out[401]}] [get_ports {fft_out[400]}] [get_ports {fft_out[399]}] [get_ports {fft_out[398]}] [get_ports {fft_out[397]}] [get_ports {fft_out[396]}] [get_ports {fft_out[395]}] [get_ports {fft_out[394]}] [get_ports {fft_out[393]}] [get_ports {fft_out[392]}] [get_ports {fft_out[391]}] [get_ports {fft_out[390]}] [get_ports {fft_out[389]}] [get_ports {fft_out[388]}] [get_ports {fft_out[387]}] [get_ports {fft_out[386]}] [get_ports {fft_out[385]}] [get_ports {fft_out[384]}] [get_ports {fft_out[383]}] [get_ports {fft_out[382]}] [get_ports {fft_out[381]}] [get_ports {fft_out[380]}] [get_ports {fft_out[379]}] [get_ports {fft_out[378]}] [get_ports {fft_out[377]}] [get_ports {fft_out[376]}] [get_ports {fft_out[375]}] [get_ports {fft_out[374]}] [get_ports {fft_out[373]}] [get_ports {fft_out[372]}] [get_ports {fft_out[371]}] [get_ports {fft_out[370]}] [get_ports {fft_out[369]}] [get_ports {fft_out[368]}] [get_ports {fft_out[367]}] [get_ports {fft_out[366]}] [get_ports {fft_out[365]}] [get_ports {fft_out[364]}] [get_ports {fft_out[363]}] [get_ports {fft_out[362]}] [get_ports {fft_out[361]}] [get_ports {fft_out[360]}] [get_ports {fft_out[359]}] [get_ports {fft_out[358]}] [get_ports {fft_out[357]}] [get_ports {fft_out[356]}] [get_ports {fft_out[355]}] [get_ports {fft_out[354]}] [get_ports {fft_out[353]}] [get_ports {fft_out[352]}] [get_ports {fft_out[351]}] [get_ports {fft_out[350]}] [get_ports {fft_out[349]}] [get_ports {fft_out[348]}] [get_ports {fft_out[347]}] [get_ports {fft_out[346]}] [get_ports {fft_out[345]}] [get_ports {fft_out[344]}] [get_ports {fft_out[343]}] [get_ports {fft_out[342]}] [get_ports {fft_out[341]}] [get_ports {fft_out[340]}] [get_ports {fft_out[339]}] [get_ports {fft_out[338]}] [get_ports {fft_out[337]}] [get_ports {fft_out[336]}] [get_ports {fft_out[335]}] [get_ports {fft_out[334]}] [get_ports {fft_out[333]}] [get_ports {fft_out[332]}] [get_ports {fft_out[331]}] [get_ports {fft_out[330]}] [get_ports {fft_out[329]}] [get_ports {fft_out[328]}] [get_ports {fft_out[327]}] [get_ports {fft_out[326]}] [get_ports {fft_out[325]}] [get_ports {fft_out[324]}] [get_ports {fft_out[323]}] [get_ports {fft_out[322]}] [get_ports {fft_out[321]}] [get_ports {fft_out[320]}] [get_ports {fft_out[319]}] [get_ports {fft_out[318]}] [get_ports {fft_out[317]}] [get_ports {fft_out[316]}] [get_ports {fft_out[315]}] [get_ports {fft_out[314]}] [get_ports {fft_out[313]}] [get_ports {fft_out[312]}] [get_ports {fft_out[311]}] [get_ports {fft_out[310]}] [get_ports {fft_out[309]}] [get_ports {fft_out[308]}] [get_ports {fft_out[307]}] [get_ports {fft_out[306]}] [get_ports {fft_out[305]}] [get_ports {fft_out[304]}] [get_ports {fft_out[303]}] [get_ports {fft_out[302]}] [get_ports {fft_out[301]}] [get_ports {fft_out[300]}] [get_ports {fft_out[299]}] [get_ports {fft_out[298]}] [get_ports {fft_out[297]}] [get_ports {fft_out[296]}] [get_ports {fft_out[295]}] [get_ports {fft_out[294]}] [get_ports {fft_out[293]}] [get_ports {fft_out[292]}] [get_ports {fft_out[291]}] [get_ports {fft_out[290]}] [get_ports {fft_out[289]}] [get_ports {fft_out[288]}] [get_ports {fft_out[287]}] [get_ports {fft_out[286]}] [get_ports {fft_out[285]}] [get_ports {fft_out[284]}] [get_ports {fft_out[283]}] [get_ports {fft_out[282]}] [get_ports {fft_out[281]}] [get_ports {fft_out[280]}] [get_ports {fft_out[279]}] [get_ports {fft_out[278]}] [get_ports {fft_out[277]}] [get_ports {fft_out[276]}] [get_ports {fft_out[275]}] [get_ports {fft_out[274]}] [get_ports {fft_out[273]}] [get_ports {fft_out[272]}] [get_ports {fft_out[271]}] [get_ports {fft_out[270]}] [get_ports {fft_out[269]}] [get_ports {fft_out[268]}] [get_ports {fft_out[267]}] [get_ports {fft_out[266]}] [get_ports {fft_out[265]}] [get_ports {fft_out[264]}] [get_ports {fft_out[263]}] [get_ports {fft_out[262]}] [get_ports {fft_out[261]}] [get_ports {fft_out[260]}] [get_ports {fft_out[259]}] [get_ports {fft_out[258]}] [get_ports {fft_out[257]}] [get_ports {fft_out[256]}] [get_ports {fft_out[255]}] [get_ports {fft_out[254]}] [get_ports {fft_out[253]}] [get_ports {fft_out[252]}] [get_ports {fft_out[251]}] [get_ports {fft_out[250]}] [get_ports {fft_out[249]}] [get_ports {fft_out[248]}] [get_ports {fft_out[247]}] [get_ports {fft_out[246]}] [get_ports {fft_out[245]}] [get_ports {fft_out[244]}] [get_ports {fft_out[243]}] [get_ports {fft_out[242]}] [get_ports {fft_out[241]}] [get_ports {fft_out[240]}] [get_ports {fft_out[239]}] [get_ports {fft_out[238]}] [get_ports {fft_out[237]}] [get_ports {fft_out[236]}] [get_ports {fft_out[235]}] [get_ports {fft_out[234]}] [get_ports {fft_out[233]}] [get_ports {fft_out[232]}] [get_ports {fft_out[231]}] [get_ports {fft_out[230]}] [get_ports {fft_out[229]}] [get_ports {fft_out[228]}] [get_ports {fft_out[227]}] [get_ports {fft_out[226]}] [get_ports {fft_out[225]}] [get_ports {fft_out[224]}] [get_ports {fft_out[223]}] [get_ports {fft_out[222]}] [get_ports {fft_out[221]}] [get_ports {fft_out[220]}] [get_ports {fft_out[219]}] [get_ports {fft_out[218]}] [get_ports {fft_out[217]}] [get_ports {fft_out[216]}] [get_ports {fft_out[215]}] [get_ports {fft_out[214]}] [get_ports {fft_out[213]}] [get_ports {fft_out[212]}] [get_ports {fft_out[211]}] [get_ports {fft_out[210]}] [get_ports {fft_out[209]}] [get_ports {fft_out[208]}] [get_ports {fft_out[207]}] [get_ports {fft_out[206]}] [get_ports {fft_out[205]}] [get_ports {fft_out[204]}] [get_ports {fft_out[203]}] [get_ports {fft_out[202]}] [get_ports {fft_out[201]}] [get_ports {fft_out[200]}] [get_ports {fft_out[199]}] [get_ports {fft_out[198]}] [get_ports {fft_out[197]}] [get_ports {fft_out[196]}] [get_ports {fft_out[195]}] [get_ports {fft_out[194]}] [get_ports {fft_out[193]}] [get_ports {fft_out[192]}] [get_ports {fft_out[191]}] [get_ports {fft_out[190]}] [get_ports {fft_out[189]}] [get_ports {fft_out[188]}] [get_ports {fft_out[187]}] [get_ports {fft_out[186]}] [get_ports {fft_out[185]}] [get_ports {fft_out[184]}] [get_ports {fft_out[183]}] [get_ports {fft_out[182]}] [get_ports {fft_out[181]}] [get_ports {fft_out[180]}] [get_ports {fft_out[179]}] [get_ports {fft_out[178]}] [get_ports {fft_out[177]}] [get_ports {fft_out[176]}] [get_ports {fft_out[175]}] [get_ports {fft_out[174]}] [get_ports {fft_out[173]}] [get_ports {fft_out[172]}] [get_ports {fft_out[171]}] [get_ports {fft_out[170]}] [get_ports {fft_out[169]}] [get_ports {fft_out[168]}] [get_ports {fft_out[167]}] [get_ports {fft_out[166]}] [get_ports {fft_out[165]}] [get_ports {fft_out[164]}] [get_ports {fft_out[163]}] [get_ports {fft_out[162]}] [get_ports {fft_out[161]}] [get_ports {fft_out[160]}] [get_ports {fft_out[159]}] [get_ports {fft_out[158]}] [get_ports {fft_out[157]}] [get_ports {fft_out[156]}] [get_ports {fft_out[155]}] [get_ports {fft_out[154]}] [get_ports {fft_out[153]}] [get_ports {fft_out[152]}] [get_ports {fft_out[151]}] [get_ports {fft_out[150]}] [get_ports {fft_out[149]}] [get_ports {fft_out[148]}] [get_ports {fft_out[147]}] [get_ports {fft_out[146]}] [get_ports {fft_out[145]}] [get_ports {fft_out[144]}] [get_ports {fft_out[143]}] [get_ports {fft_out[142]}] [get_ports {fft_out[141]}] [get_ports {fft_out[140]}] [get_ports {fft_out[139]}] [get_ports {fft_out[138]}] [get_ports {fft_out[137]}] [get_ports {fft_out[136]}] [get_ports {fft_out[135]}] [get_ports {fft_out[134]}] [get_ports {fft_out[133]}] [get_ports {fft_out[132]}] [get_ports {fft_out[131]}] [get_ports {fft_out[130]}] [get_ports {fft_out[129]}] [get_ports {fft_out[128]}] [get_ports {fft_out[127]}] [get_ports {fft_out[126]}] [get_ports {fft_out[125]}] [get_ports {fft_out[124]}] [get_ports {fft_out[123]}] [get_ports {fft_out[122]}] [get_ports {fft_out[121]}] [get_ports {fft_out[120]}] [get_ports {fft_out[119]}] [get_ports {fft_out[118]}] [get_ports {fft_out[117]}] [get_ports {fft_out[116]}] [get_ports {fft_out[115]}] [get_ports {fft_out[114]}] [get_ports {fft_out[113]}] [get_ports {fft_out[112]}] [get_ports {fft_out[111]}] [get_ports {fft_out[110]}] [get_ports {fft_out[109]}] [get_ports {fft_out[108]}] [get_ports {fft_out[107]}] [get_ports {fft_out[106]}] [get_ports {fft_out[105]}] [get_ports {fft_out[104]}] [get_ports {fft_out[103]}] [get_ports {fft_out[102]}] [get_ports {fft_out[101]}] [get_ports {fft_out[100]}] [get_ports {fft_out[99]}] [get_ports {fft_out[98]}] [get_ports {fft_out[97]}] [get_ports {fft_out[96]}] [get_ports {fft_out[95]}] [get_ports {fft_out[94]}] [get_ports {fft_out[93]}] [get_ports {fft_out[92]}] [get_ports {fft_out[91]}] [get_ports {fft_out[90]}] [get_ports {fft_out[89]}] [get_ports {fft_out[88]}] [get_ports {fft_out[87]}] [get_ports {fft_out[86]}] [get_ports {fft_out[85]}] [get_ports {fft_out[84]}] [get_ports {fft_out[83]}] [get_ports {fft_out[82]}] [get_ports {fft_out[81]}] [get_ports {fft_out[80]}] [get_ports {fft_out[79]}] [get_ports {fft_out[78]}] [get_ports {fft_out[77]}] [get_ports {fft_out[76]}] [get_ports {fft_out[75]}] [get_ports {fft_out[74]}] [get_ports {fft_out[73]}] [get_ports {fft_out[72]}] [get_ports {fft_out[71]}] [get_ports {fft_out[70]}] [get_ports {fft_out[69]}] [get_ports {fft_out[68]}] [get_ports {fft_out[67]}] [get_ports {fft_out[66]}] [get_ports {fft_out[65]}] [get_ports {fft_out[64]}] [get_ports {fft_out[63]}] [get_ports {fft_out[62]}] [get_ports {fft_out[61]}] [get_ports {fft_out[60]}] [get_ports {fft_out[59]}] [get_ports {fft_out[58]}] [get_ports {fft_out[57]}] [get_ports {fft_out[56]}] [get_ports {fft_out[55]}] [get_ports {fft_out[54]}] [get_ports {fft_out[53]}] [get_ports {fft_out[52]}] [get_ports {fft_out[51]}] [get_ports {fft_out[50]}] [get_ports {fft_out[49]}] [get_ports {fft_out[48]}] [get_ports {fft_out[47]}] [get_ports {fft_out[46]}] [get_ports {fft_out[45]}] [get_ports {fft_out[44]}] [get_ports {fft_out[43]}] [get_ports {fft_out[42]}] [get_ports {fft_out[41]}] [get_ports {fft_out[40]}] [get_ports {fft_out[39]}] [get_ports {fft_out[38]}] [get_ports {fft_out[37]}] [get_ports {fft_out[36]}] [get_ports {fft_out[35]}] [get_ports {fft_out[34]}] [get_ports {fft_out[33]}] [get_ports {fft_out[32]}] [get_ports {fft_out[31]}] [get_ports {fft_out[30]}] [get_ports {fft_out[29]}] [get_ports {fft_out[28]}] [get_ports {fft_out[27]}] [get_ports {fft_out[26]}] [get_ports {fft_out[25]}] [get_ports {fft_out[24]}] [get_ports {fft_out[23]}] [get_ports {fft_out[22]}] [get_ports {fft_out[21]}] [get_ports {fft_out[20]}] [get_ports {fft_out[19]}] [get_ports {fft_out[18]}] [get_ports {fft_out[17]}] [get_ports {fft_out[16]}] [get_ports {fft_out[15]}] [get_ports {fft_out[14]}] [get_ports {fft_out[13]}] [get_ports {fft_out[12]}] [get_ports {fft_out[11]}] [get_ports {fft_out[10]}] [get_ports {fft_out[9]}] [get_ports {fft_out[8]}] [get_ports {fft_out[7]}] [get_ports {fft_out[6]}] [get_ports {fft_out[5]}] [get_ports {fft_out[4]}] [get_ports {fft_out[3]}] [get_ports {fft_out[2]}] [get_ports {fft_out[1]}] [get_ports {fft_out[0]}] [get_ports output_mode] [get_ports out_valid]]
group_path -name REGIN  -from [get_ports reset]
group_path -name REGIN  -from [list [get_ports enable] [get_ports {data_in_0[63]}] [get_ports {data_in_0[62]}] [get_ports {data_in_0[61]}] [get_ports {data_in_0[60]}] [get_ports {data_in_0[59]}] [get_ports {data_in_0[58]}] [get_ports {data_in_0[57]}] [get_ports {data_in_0[56]}] [get_ports {data_in_0[55]}] [get_ports {data_in_0[54]}] [get_ports {data_in_0[53]}] [get_ports {data_in_0[52]}] [get_ports {data_in_0[51]}] [get_ports {data_in_0[50]}] [get_ports {data_in_0[49]}] [get_ports {data_in_0[48]}] [get_ports {data_in_0[47]}] [get_ports {data_in_0[46]}] [get_ports {data_in_0[45]}] [get_ports {data_in_0[44]}] [get_ports {data_in_0[43]}] [get_ports {data_in_0[42]}] [get_ports {data_in_0[41]}] [get_ports {data_in_0[40]}] [get_ports {data_in_0[39]}] [get_ports {data_in_0[38]}] [get_ports {data_in_0[37]}] [get_ports {data_in_0[36]}] [get_ports {data_in_0[35]}] [get_ports {data_in_0[34]}] [get_ports {data_in_0[33]}] [get_ports {data_in_0[32]}] [get_ports {data_in_0[31]}] [get_ports {data_in_0[30]}] [get_ports {data_in_0[29]}] [get_ports {data_in_0[28]}] [get_ports {data_in_0[27]}] [get_ports {data_in_0[26]}] [get_ports {data_in_0[25]}] [get_ports {data_in_0[24]}] [get_ports {data_in_0[23]}] [get_ports {data_in_0[22]}] [get_ports {data_in_0[21]}] [get_ports {data_in_0[20]}] [get_ports {data_in_0[19]}] [get_ports {data_in_0[18]}] [get_ports {data_in_0[17]}] [get_ports {data_in_0[16]}] [get_ports {data_in_0[15]}] [get_ports {data_in_0[14]}] [get_ports {data_in_0[13]}] [get_ports {data_in_0[12]}] [get_ports {data_in_0[11]}] [get_ports {data_in_0[10]}] [get_ports {data_in_0[9]}] [get_ports {data_in_0[8]}] [get_ports {data_in_0[7]}] [get_ports {data_in_0[6]}] [get_ports {data_in_0[5]}] [get_ports {data_in_0[4]}] [get_ports {data_in_0[3]}] [get_ports {data_in_0[2]}] [get_ports {data_in_0[1]}] [get_ports {data_in_0[0]}] [get_ports {data_in_1[63]}] [get_ports {data_in_1[62]}] [get_ports {data_in_1[61]}] [get_ports {data_in_1[60]}] [get_ports {data_in_1[59]}] [get_ports {data_in_1[58]}] [get_ports {data_in_1[57]}] [get_ports {data_in_1[56]}] [get_ports {data_in_1[55]}] [get_ports {data_in_1[54]}] [get_ports {data_in_1[53]}] [get_ports {data_in_1[52]}] [get_ports {data_in_1[51]}] [get_ports {data_in_1[50]}] [get_ports {data_in_1[49]}] [get_ports {data_in_1[48]}] [get_ports {data_in_1[47]}] [get_ports {data_in_1[46]}] [get_ports {data_in_1[45]}] [get_ports {data_in_1[44]}] [get_ports {data_in_1[43]}] [get_ports {data_in_1[42]}] [get_ports {data_in_1[41]}] [get_ports {data_in_1[40]}] [get_ports {data_in_1[39]}] [get_ports {data_in_1[38]}] [get_ports {data_in_1[37]}] [get_ports {data_in_1[36]}] [get_ports {data_in_1[35]}] [get_ports {data_in_1[34]}] [get_ports {data_in_1[33]}] [get_ports {data_in_1[32]}] [get_ports {data_in_1[31]}] [get_ports {data_in_1[30]}] [get_ports {data_in_1[29]}] [get_ports {data_in_1[28]}] [get_ports {data_in_1[27]}] [get_ports {data_in_1[26]}] [get_ports {data_in_1[25]}] [get_ports {data_in_1[24]}] [get_ports {data_in_1[23]}] [get_ports {data_in_1[22]}] [get_ports {data_in_1[21]}] [get_ports {data_in_1[20]}] [get_ports {data_in_1[19]}] [get_ports {data_in_1[18]}] [get_ports {data_in_1[17]}] [get_ports {data_in_1[16]}] [get_ports {data_in_1[15]}] [get_ports {data_in_1[14]}] [get_ports {data_in_1[13]}] [get_ports {data_in_1[12]}] [get_ports {data_in_1[11]}] [get_ports {data_in_1[10]}] [get_ports {data_in_1[9]}] [get_ports {data_in_1[8]}] [get_ports {data_in_1[7]}] [get_ports {data_in_1[6]}] [get_ports {data_in_1[5]}] [get_ports {data_in_1[4]}] [get_ports {data_in_1[3]}] [get_ports {data_in_1[2]}] [get_ports {data_in_1[1]}] [get_ports {data_in_1[0]}]]
group_path -name REGOUT  -to [list [get_ports {fft_out[511]}] [get_ports {fft_out[510]}] [get_ports {fft_out[509]}] [get_ports {fft_out[508]}] [get_ports {fft_out[507]}] [get_ports {fft_out[506]}] [get_ports {fft_out[505]}] [get_ports {fft_out[504]}] [get_ports {fft_out[503]}] [get_ports {fft_out[502]}] [get_ports {fft_out[501]}] [get_ports {fft_out[500]}] [get_ports {fft_out[499]}] [get_ports {fft_out[498]}] [get_ports {fft_out[497]}] [get_ports {fft_out[496]}] [get_ports {fft_out[495]}] [get_ports {fft_out[494]}] [get_ports {fft_out[493]}] [get_ports {fft_out[492]}] [get_ports {fft_out[491]}] [get_ports {fft_out[490]}] [get_ports {fft_out[489]}] [get_ports {fft_out[488]}] [get_ports {fft_out[487]}] [get_ports {fft_out[486]}] [get_ports {fft_out[485]}] [get_ports {fft_out[484]}] [get_ports {fft_out[483]}] [get_ports {fft_out[482]}] [get_ports {fft_out[481]}] [get_ports {fft_out[480]}] [get_ports {fft_out[479]}] [get_ports {fft_out[478]}] [get_ports {fft_out[477]}] [get_ports {fft_out[476]}] [get_ports {fft_out[475]}] [get_ports {fft_out[474]}] [get_ports {fft_out[473]}] [get_ports {fft_out[472]}] [get_ports {fft_out[471]}] [get_ports {fft_out[470]}] [get_ports {fft_out[469]}] [get_ports {fft_out[468]}] [get_ports {fft_out[467]}] [get_ports {fft_out[466]}] [get_ports {fft_out[465]}] [get_ports {fft_out[464]}] [get_ports {fft_out[463]}] [get_ports {fft_out[462]}] [get_ports {fft_out[461]}] [get_ports {fft_out[460]}] [get_ports {fft_out[459]}] [get_ports {fft_out[458]}] [get_ports {fft_out[457]}] [get_ports {fft_out[456]}] [get_ports {fft_out[455]}] [get_ports {fft_out[454]}] [get_ports {fft_out[453]}] [get_ports {fft_out[452]}] [get_ports {fft_out[451]}] [get_ports {fft_out[450]}] [get_ports {fft_out[449]}] [get_ports {fft_out[448]}] [get_ports {fft_out[447]}] [get_ports {fft_out[446]}] [get_ports {fft_out[445]}] [get_ports {fft_out[444]}] [get_ports {fft_out[443]}] [get_ports {fft_out[442]}] [get_ports {fft_out[441]}] [get_ports {fft_out[440]}] [get_ports {fft_out[439]}] [get_ports {fft_out[438]}] [get_ports {fft_out[437]}] [get_ports {fft_out[436]}] [get_ports {fft_out[435]}] [get_ports {fft_out[434]}] [get_ports {fft_out[433]}] [get_ports {fft_out[432]}] [get_ports {fft_out[431]}] [get_ports {fft_out[430]}] [get_ports {fft_out[429]}] [get_ports {fft_out[428]}] [get_ports {fft_out[427]}] [get_ports {fft_out[426]}] [get_ports {fft_out[425]}] [get_ports {fft_out[424]}] [get_ports {fft_out[423]}] [get_ports {fft_out[422]}] [get_ports {fft_out[421]}] [get_ports {fft_out[420]}] [get_ports {fft_out[419]}] [get_ports {fft_out[418]}] [get_ports {fft_out[417]}] [get_ports {fft_out[416]}] [get_ports {fft_out[415]}] [get_ports {fft_out[414]}] [get_ports {fft_out[413]}] [get_ports {fft_out[412]}] [get_ports {fft_out[411]}] [get_ports {fft_out[410]}] [get_ports {fft_out[409]}] [get_ports {fft_out[408]}] [get_ports {fft_out[407]}] [get_ports {fft_out[406]}] [get_ports {fft_out[405]}] [get_ports {fft_out[404]}] [get_ports {fft_out[403]}] [get_ports {fft_out[402]}] [get_ports {fft_out[401]}] [get_ports {fft_out[400]}] [get_ports {fft_out[399]}] [get_ports {fft_out[398]}] [get_ports {fft_out[397]}] [get_ports {fft_out[396]}] [get_ports {fft_out[395]}] [get_ports {fft_out[394]}] [get_ports {fft_out[393]}] [get_ports {fft_out[392]}] [get_ports {fft_out[391]}] [get_ports {fft_out[390]}] [get_ports {fft_out[389]}] [get_ports {fft_out[388]}] [get_ports {fft_out[387]}] [get_ports {fft_out[386]}] [get_ports {fft_out[385]}] [get_ports {fft_out[384]}] [get_ports {fft_out[383]}] [get_ports {fft_out[382]}] [get_ports {fft_out[381]}] [get_ports {fft_out[380]}] [get_ports {fft_out[379]}] [get_ports {fft_out[378]}] [get_ports {fft_out[377]}] [get_ports {fft_out[376]}] [get_ports {fft_out[375]}] [get_ports {fft_out[374]}] [get_ports {fft_out[373]}] [get_ports {fft_out[372]}] [get_ports {fft_out[371]}] [get_ports {fft_out[370]}] [get_ports {fft_out[369]}] [get_ports {fft_out[368]}] [get_ports {fft_out[367]}] [get_ports {fft_out[366]}] [get_ports {fft_out[365]}] [get_ports {fft_out[364]}] [get_ports {fft_out[363]}] [get_ports {fft_out[362]}] [get_ports {fft_out[361]}] [get_ports {fft_out[360]}] [get_ports {fft_out[359]}] [get_ports {fft_out[358]}] [get_ports {fft_out[357]}] [get_ports {fft_out[356]}] [get_ports {fft_out[355]}] [get_ports {fft_out[354]}] [get_ports {fft_out[353]}] [get_ports {fft_out[352]}] [get_ports {fft_out[351]}] [get_ports {fft_out[350]}] [get_ports {fft_out[349]}] [get_ports {fft_out[348]}] [get_ports {fft_out[347]}] [get_ports {fft_out[346]}] [get_ports {fft_out[345]}] [get_ports {fft_out[344]}] [get_ports {fft_out[343]}] [get_ports {fft_out[342]}] [get_ports {fft_out[341]}] [get_ports {fft_out[340]}] [get_ports {fft_out[339]}] [get_ports {fft_out[338]}] [get_ports {fft_out[337]}] [get_ports {fft_out[336]}] [get_ports {fft_out[335]}] [get_ports {fft_out[334]}] [get_ports {fft_out[333]}] [get_ports {fft_out[332]}] [get_ports {fft_out[331]}] [get_ports {fft_out[330]}] [get_ports {fft_out[329]}] [get_ports {fft_out[328]}] [get_ports {fft_out[327]}] [get_ports {fft_out[326]}] [get_ports {fft_out[325]}] [get_ports {fft_out[324]}] [get_ports {fft_out[323]}] [get_ports {fft_out[322]}] [get_ports {fft_out[321]}] [get_ports {fft_out[320]}] [get_ports {fft_out[319]}] [get_ports {fft_out[318]}] [get_ports {fft_out[317]}] [get_ports {fft_out[316]}] [get_ports {fft_out[315]}] [get_ports {fft_out[314]}] [get_ports {fft_out[313]}] [get_ports {fft_out[312]}] [get_ports {fft_out[311]}] [get_ports {fft_out[310]}] [get_ports {fft_out[309]}] [get_ports {fft_out[308]}] [get_ports {fft_out[307]}] [get_ports {fft_out[306]}] [get_ports {fft_out[305]}] [get_ports {fft_out[304]}] [get_ports {fft_out[303]}] [get_ports {fft_out[302]}] [get_ports {fft_out[301]}] [get_ports {fft_out[300]}] [get_ports {fft_out[299]}] [get_ports {fft_out[298]}] [get_ports {fft_out[297]}] [get_ports {fft_out[296]}] [get_ports {fft_out[295]}] [get_ports {fft_out[294]}] [get_ports {fft_out[293]}] [get_ports {fft_out[292]}] [get_ports {fft_out[291]}] [get_ports {fft_out[290]}] [get_ports {fft_out[289]}] [get_ports {fft_out[288]}] [get_ports {fft_out[287]}] [get_ports {fft_out[286]}] [get_ports {fft_out[285]}] [get_ports {fft_out[284]}] [get_ports {fft_out[283]}] [get_ports {fft_out[282]}] [get_ports {fft_out[281]}] [get_ports {fft_out[280]}] [get_ports {fft_out[279]}] [get_ports {fft_out[278]}] [get_ports {fft_out[277]}] [get_ports {fft_out[276]}] [get_ports {fft_out[275]}] [get_ports {fft_out[274]}] [get_ports {fft_out[273]}] [get_ports {fft_out[272]}] [get_ports {fft_out[271]}] [get_ports {fft_out[270]}] [get_ports {fft_out[269]}] [get_ports {fft_out[268]}] [get_ports {fft_out[267]}] [get_ports {fft_out[266]}] [get_ports {fft_out[265]}] [get_ports {fft_out[264]}] [get_ports {fft_out[263]}] [get_ports {fft_out[262]}] [get_ports {fft_out[261]}] [get_ports {fft_out[260]}] [get_ports {fft_out[259]}] [get_ports {fft_out[258]}] [get_ports {fft_out[257]}] [get_ports {fft_out[256]}] [get_ports {fft_out[255]}] [get_ports {fft_out[254]}] [get_ports {fft_out[253]}] [get_ports {fft_out[252]}] [get_ports {fft_out[251]}] [get_ports {fft_out[250]}] [get_ports {fft_out[249]}] [get_ports {fft_out[248]}] [get_ports {fft_out[247]}] [get_ports {fft_out[246]}] [get_ports {fft_out[245]}] [get_ports {fft_out[244]}] [get_ports {fft_out[243]}] [get_ports {fft_out[242]}] [get_ports {fft_out[241]}] [get_ports {fft_out[240]}] [get_ports {fft_out[239]}] [get_ports {fft_out[238]}] [get_ports {fft_out[237]}] [get_ports {fft_out[236]}] [get_ports {fft_out[235]}] [get_ports {fft_out[234]}] [get_ports {fft_out[233]}] [get_ports {fft_out[232]}] [get_ports {fft_out[231]}] [get_ports {fft_out[230]}] [get_ports {fft_out[229]}] [get_ports {fft_out[228]}] [get_ports {fft_out[227]}] [get_ports {fft_out[226]}] [get_ports {fft_out[225]}] [get_ports {fft_out[224]}] [get_ports {fft_out[223]}] [get_ports {fft_out[222]}] [get_ports {fft_out[221]}] [get_ports {fft_out[220]}] [get_ports {fft_out[219]}] [get_ports {fft_out[218]}] [get_ports {fft_out[217]}] [get_ports {fft_out[216]}] [get_ports {fft_out[215]}] [get_ports {fft_out[214]}] [get_ports {fft_out[213]}] [get_ports {fft_out[212]}] [get_ports {fft_out[211]}] [get_ports {fft_out[210]}] [get_ports {fft_out[209]}] [get_ports {fft_out[208]}] [get_ports {fft_out[207]}] [get_ports {fft_out[206]}] [get_ports {fft_out[205]}] [get_ports {fft_out[204]}] [get_ports {fft_out[203]}] [get_ports {fft_out[202]}] [get_ports {fft_out[201]}] [get_ports {fft_out[200]}] [get_ports {fft_out[199]}] [get_ports {fft_out[198]}] [get_ports {fft_out[197]}] [get_ports {fft_out[196]}] [get_ports {fft_out[195]}] [get_ports {fft_out[194]}] [get_ports {fft_out[193]}] [get_ports {fft_out[192]}] [get_ports {fft_out[191]}] [get_ports {fft_out[190]}] [get_ports {fft_out[189]}] [get_ports {fft_out[188]}] [get_ports {fft_out[187]}] [get_ports {fft_out[186]}] [get_ports {fft_out[185]}] [get_ports {fft_out[184]}] [get_ports {fft_out[183]}] [get_ports {fft_out[182]}] [get_ports {fft_out[181]}] [get_ports {fft_out[180]}] [get_ports {fft_out[179]}] [get_ports {fft_out[178]}] [get_ports {fft_out[177]}] [get_ports {fft_out[176]}] [get_ports {fft_out[175]}] [get_ports {fft_out[174]}] [get_ports {fft_out[173]}] [get_ports {fft_out[172]}] [get_ports {fft_out[171]}] [get_ports {fft_out[170]}] [get_ports {fft_out[169]}] [get_ports {fft_out[168]}] [get_ports {fft_out[167]}] [get_ports {fft_out[166]}] [get_ports {fft_out[165]}] [get_ports {fft_out[164]}] [get_ports {fft_out[163]}] [get_ports {fft_out[162]}] [get_ports {fft_out[161]}] [get_ports {fft_out[160]}] [get_ports {fft_out[159]}] [get_ports {fft_out[158]}] [get_ports {fft_out[157]}] [get_ports {fft_out[156]}] [get_ports {fft_out[155]}] [get_ports {fft_out[154]}] [get_ports {fft_out[153]}] [get_ports {fft_out[152]}] [get_ports {fft_out[151]}] [get_ports {fft_out[150]}] [get_ports {fft_out[149]}] [get_ports {fft_out[148]}] [get_ports {fft_out[147]}] [get_ports {fft_out[146]}] [get_ports {fft_out[145]}] [get_ports {fft_out[144]}] [get_ports {fft_out[143]}] [get_ports {fft_out[142]}] [get_ports {fft_out[141]}] [get_ports {fft_out[140]}] [get_ports {fft_out[139]}] [get_ports {fft_out[138]}] [get_ports {fft_out[137]}] [get_ports {fft_out[136]}] [get_ports {fft_out[135]}] [get_ports {fft_out[134]}] [get_ports {fft_out[133]}] [get_ports {fft_out[132]}] [get_ports {fft_out[131]}] [get_ports {fft_out[130]}] [get_ports {fft_out[129]}] [get_ports {fft_out[128]}] [get_ports {fft_out[127]}] [get_ports {fft_out[126]}] [get_ports {fft_out[125]}] [get_ports {fft_out[124]}] [get_ports {fft_out[123]}] [get_ports {fft_out[122]}] [get_ports {fft_out[121]}] [get_ports {fft_out[120]}] [get_ports {fft_out[119]}] [get_ports {fft_out[118]}] [get_ports {fft_out[117]}] [get_ports {fft_out[116]}] [get_ports {fft_out[115]}] [get_ports {fft_out[114]}] [get_ports {fft_out[113]}] [get_ports {fft_out[112]}] [get_ports {fft_out[111]}] [get_ports {fft_out[110]}] [get_ports {fft_out[109]}] [get_ports {fft_out[108]}] [get_ports {fft_out[107]}] [get_ports {fft_out[106]}] [get_ports {fft_out[105]}] [get_ports {fft_out[104]}] [get_ports {fft_out[103]}] [get_ports {fft_out[102]}] [get_ports {fft_out[101]}] [get_ports {fft_out[100]}] [get_ports {fft_out[99]}] [get_ports {fft_out[98]}] [get_ports {fft_out[97]}] [get_ports {fft_out[96]}] [get_ports {fft_out[95]}] [get_ports {fft_out[94]}] [get_ports {fft_out[93]}] [get_ports {fft_out[92]}] [get_ports {fft_out[91]}] [get_ports {fft_out[90]}] [get_ports {fft_out[89]}] [get_ports {fft_out[88]}] [get_ports {fft_out[87]}] [get_ports {fft_out[86]}] [get_ports {fft_out[85]}] [get_ports {fft_out[84]}] [get_ports {fft_out[83]}] [get_ports {fft_out[82]}] [get_ports {fft_out[81]}] [get_ports {fft_out[80]}] [get_ports {fft_out[79]}] [get_ports {fft_out[78]}] [get_ports {fft_out[77]}] [get_ports {fft_out[76]}] [get_ports {fft_out[75]}] [get_ports {fft_out[74]}] [get_ports {fft_out[73]}] [get_ports {fft_out[72]}] [get_ports {fft_out[71]}] [get_ports {fft_out[70]}] [get_ports {fft_out[69]}] [get_ports {fft_out[68]}] [get_ports {fft_out[67]}] [get_ports {fft_out[66]}] [get_ports {fft_out[65]}] [get_ports {fft_out[64]}] [get_ports {fft_out[63]}] [get_ports {fft_out[62]}] [get_ports {fft_out[61]}] [get_ports {fft_out[60]}] [get_ports {fft_out[59]}] [get_ports {fft_out[58]}] [get_ports {fft_out[57]}] [get_ports {fft_out[56]}] [get_ports {fft_out[55]}] [get_ports {fft_out[54]}] [get_ports {fft_out[53]}] [get_ports {fft_out[52]}] [get_ports {fft_out[51]}] [get_ports {fft_out[50]}] [get_ports {fft_out[49]}] [get_ports {fft_out[48]}] [get_ports {fft_out[47]}] [get_ports {fft_out[46]}] [get_ports {fft_out[45]}] [get_ports {fft_out[44]}] [get_ports {fft_out[43]}] [get_ports {fft_out[42]}] [get_ports {fft_out[41]}] [get_ports {fft_out[40]}] [get_ports {fft_out[39]}] [get_ports {fft_out[38]}] [get_ports {fft_out[37]}] [get_ports {fft_out[36]}] [get_ports {fft_out[35]}] [get_ports {fft_out[34]}] [get_ports {fft_out[33]}] [get_ports {fft_out[32]}] [get_ports {fft_out[31]}] [get_ports {fft_out[30]}] [get_ports {fft_out[29]}] [get_ports {fft_out[28]}] [get_ports {fft_out[27]}] [get_ports {fft_out[26]}] [get_ports {fft_out[25]}] [get_ports {fft_out[24]}] [get_ports {fft_out[23]}] [get_ports {fft_out[22]}] [get_ports {fft_out[21]}] [get_ports {fft_out[20]}] [get_ports {fft_out[19]}] [get_ports {fft_out[18]}] [get_ports {fft_out[17]}] [get_ports {fft_out[16]}] [get_ports {fft_out[15]}] [get_ports {fft_out[14]}] [get_ports {fft_out[13]}] [get_ports {fft_out[12]}] [get_ports {fft_out[11]}] [get_ports {fft_out[10]}] [get_ports {fft_out[9]}] [get_ports {fft_out[8]}] [get_ports {fft_out[7]}] [get_ports {fft_out[6]}] [get_ports {fft_out[5]}] [get_ports {fft_out[4]}] [get_ports {fft_out[3]}] [get_ports {fft_out[2]}] [get_ports {fft_out[1]}] [get_ports {fft_out[0]}] [get_ports output_mode] [get_ports out_valid]]
set_false_path   -from [get_ports reset]
